-- ============================================================
-- INSURANCE AI HUB (E.D.I.E.) - External Enrichment Datasets
-- Snowflake Marketplace Recommendations
-- ============================================================
-- 
-- These datasets can be layered onto your INSURANCE_AI_HUB
-- to enrich analytics, risk models, and AI agent responses.
--
-- ============================================================
-- CATEGORY 1: WEATHER & NATURAL DISASTER (Claims Correlation)
-- Join on: STATE, ZIP_CODE, CLAIM_DATE
-- ============================================================
--
-- 1. Severe Weather Data Inventory (FREE)
--    Provider: Element Data
--    Global Name: GZSTZJUPD05
--    URL: https://app.snowflake.com/marketplace/listing/GZSTZJUPD05
--    Description: NOAA severe weather records (US). Storms, hail, tornadoes.
--    Use Case: Correlate CLAIMS.CLAIM_DATE + INCIDENT_LOCATION with storm events
--              to validate weather-related claims and detect fraud.
--
-- 2. FEMA National Risk Index (FREE)
--    Provider: kipi.ai
--    Global Name: GZSTZKU9FH9
--    URL: https://app.snowflake.com/marketplace/listing/GZSTZKU9FH9
--    Description: Risk scores for natural hazards + socioeconomic factors across US.
--    Use Case: Enrich CUSTOMERS by ZIP to score natural disaster exposure,
--              feed into AT_RISK_POLICIES churn models.
--
-- 3. Climate Risk Analytics (PAID)
--    Provider: Cotality (CoreLogic)
--    Global Name: GZSTZ6N0IFG
--    URL: https://app.snowflake.com/marketplace/listing/GZSTZ6N0IFG
--    Description: Parcel-level climate risk scores (earthquake, wildfire, flood, wind).
--    Use Case: Underwriting score enrichment for Home/Commercial policies.
--
-- ============================================================
-- CATEGORY 2: DEMOGRAPHICS & CENSUS (Customer Segmentation)
-- Join on: ZIP_CODE, STATE
-- ============================================================
--
-- 4. US Census Data & Demographic Insights (FREE)
--    Provider: aterio
--    Global Name: GZTSZ10H0398
--    URL: https://app.snowflake.com/marketplace/listing/GZTSZ10H0398
--    Description: ZIP-level demographics, historical + forecast trends.
--    Use Case: Enrich CUSTOMERS with income brackets, age distributions,
--              household size for segmentation and premium optimization.
--
-- 5. ZIP Code Insights - US Demographics & Economics (PAID)
--    Provider: No Fret Data (Census Galaxy)
--    Global Name: GZ1M6ZYDCEH
--    URL: https://app.snowflake.com/marketplace/listing/GZ1M6ZYDCEH
--    Description: 2023 Census demographics + geospatial for 39,000+ ZIP codes.
--    Use Case: AI/ML-ready features for churn prediction, risk tier refinement.
--
-- 6. Snowflake Public Data (FREE - 90+ sources)
--    Provider: Snowflake Public Data Products
--    Global Name: GZTSZ290BV255
--    URL: https://app.snowflake.com/marketplace/listing/GZTSZ290BV255
--    Description: Curated public domain data (census, economic, geographic).
--    Use Case: Broad enrichment layer for multiple analytics use cases.
--
-- ============================================================
-- CATEGORY 3: CRIME & RISK (Auto/Home Risk Scoring)
-- Join on: ZIP_CODE, STATE, CITY
-- ============================================================
--
-- 7. CrimeIndex (PAID)
--    Provider: Precisely
--    Global Name: GZT0Z2BR4AC9M
--    URL: https://app.snowflake.com/marketplace/listing/GZT0Z2BR4AC9M
--    Description: Crime risk scores by 11 crime types at Census block group level.
--    Use Case: Enrich Auto/Home policies with theft/vandalism/burglary risk
--              for underwriting and premium calculation.
--
-- 8. Neighborhood Crime (PAID)
--    Provider: Cotality (CoreLogic)
--    Global Name: GZSTZ6N0IG9
--    URL: https://app.snowflake.com/marketplace/listing/GZSTZ6N0IG9
--    Description: Property and violent crime stats with spatial algorithms.
--    Use Case: Home insurance risk scoring, claims fraud validation.
--
-- ============================================================
-- CATEGORY 4: INSURANCE INDUSTRY (Benchmarking & Intelligence)
-- Join on: POLICY_TYPE, STATE, time period
-- ============================================================
--
-- 9. JD Power Signals Intelligence - Personal Lines Insurance (PAID)
--    Provider: JD Power
--    Global Name: GZTSZUDI1RRJ
--    URL: https://app.snowflake.com/marketplace/listing/GZTSZUDI1RRJ
--    Description: Daily shopping/switching intelligence for auto, home, renters.
--    Use Case: Benchmark AT_RISK_POLICIES churn rates against industry,
--              validate retention strategies.
--
-- 10. FactSet U.S. Insurance Industry Financials (PAID)
--     Provider: FactSet
--     Global Name: GZT0ZGCQ51S3
--     URL: https://app.snowflake.com/marketplace/listing/GZT0ZGCQ51S3
--     Description: As-reported financials for insurance companies.
--     Use Case: Competitive benchmarking for loss ratios, combined ratios.
--
-- ============================================================
-- CATEGORY 5: FRAUD DETECTION (Claims Fraud Enhancement)
-- Join on: IP, transaction metadata, location
-- ============================================================
--
-- 11. Purchase Fraud Risk Application (APPLICATION)
--     Provider: Amdocs
--     Global Name: GZTYZTMYIMH
--     URL: https://app.snowflake.com/marketplace/listing/GZTYZTMYIMH
--     Description: Scores fraud risk for individual transactions.
--     Use Case: Supplement CLAIMS.FRAUD_SCORE with external risk signals.
--
-- 12. GSD (Generate Synthetic Data) - Fraud (APPLICATION)
--     Provider: FinThetic LLC
--     Global Name: GZTSZ3VI09V
--     URL: https://app.snowflake.com/marketplace/listing/GZTSZ3VI09V
--     Description: Synthetic fraud data generation for ML training.
--     Use Case: Generate additional training data for fraud detection models.
--
-- ============================================================
-- RECOMMENDED FREE STACK (No cost, immediate value):
-- ============================================================
--
-- 1. Snowflake Public Data (GZTSZ290BV255) - Census + economics
-- 2. Severe Weather Data Inventory (GZSTZJUPD05) - Storm events
-- 3. FEMA National Risk Index (GZSTZKU9FH9) - Hazard risk scores
-- 4. US Census Data & Demographics (GZTSZ10H0398) - ZIP demographics
--
-- ============================================================
-- HOW TO INSTALL A MARKETPLACE LISTING:
-- ============================================================
-- 
-- In Snowsight: Data Products > Marketplace > Search by Global Name
-- Click "Get" or "Request" > Choose database name > Done
--
-- Example query after install:
-- SELECT c.CUSTOMER_ID, c.ZIP_CODE, d.MEDIAN_INCOME, d.POPULATION
-- FROM INSURANCE_AI_HUB.ANALYTICS.CUSTOMERS c
-- JOIN <CENSUS_DB>.PUBLIC.ZIP_DEMOGRAPHICS d ON c.ZIP_CODE = d.ZIP_CODE;
