-- ============================================================
-- INSURANCE AI HUB (E.D.I.E.) - Data Exploration Queries
-- Understand the structure, relationships, and patterns
-- ============================================================

USE DATABASE INSURANCE_AI_HUB;
USE WAREHOUSE INSURANCE_AI_HUB_WH;

-- ============================================================
-- 1. FULL INVENTORY: All tables with row counts and columns
-- ============================================================
SELECT
    t.TABLE_SCHEMA,
    t.TABLE_NAME,
    t.ROW_COUNT,
    c.COL_COUNT AS COLUMN_COUNT,
    t.BYTES / 1024 / 1024 AS SIZE_MB,
    t.COMMENT
FROM INFORMATION_SCHEMA.TABLES t
LEFT JOIN (
    SELECT TABLE_SCHEMA, TABLE_NAME, COUNT(*) AS COL_COUNT
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA IN ('ANALYTICS','DOCUMENTS','DATA_QUALITY')
    GROUP BY TABLE_SCHEMA, TABLE_NAME
) c ON t.TABLE_SCHEMA = c.TABLE_SCHEMA AND t.TABLE_NAME = c.TABLE_NAME
WHERE t.TABLE_SCHEMA IN ('ANALYTICS','DOCUMENTS','DATA_QUALITY')
ORDER BY t.TABLE_SCHEMA, t.TABLE_NAME;

-- ============================================================
-- 2. COLUMN DETAILS: All 149 columns with types
-- ============================================================
SELECT
    TABLE_SCHEMA,
    TABLE_NAME,
    ORDINAL_POSITION,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA IN ('ANALYTICS','DOCUMENTS','DATA_QUALITY')
ORDER BY TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION;

-- ============================================================
-- 3. CUSTOMERS - Sample & Distribution
-- ============================================================
SELECT * FROM ANALYTICS.CUSTOMERS LIMIT 10;

SELECT RISK_TIER, COUNT(*) AS CNT, ROUND(AVG(CREDIT_SCORE)) AS AVG_CREDIT
FROM ANALYTICS.CUSTOMERS GROUP BY RISK_TIER ORDER BY CNT DESC;

SELECT SEGMENT, COUNT(*) AS CNT FROM ANALYTICS.CUSTOMERS GROUP BY SEGMENT ORDER BY CNT DESC;

SELECT STATE, COUNT(*) AS CNT FROM ANALYTICS.CUSTOMERS GROUP BY STATE ORDER BY CNT DESC LIMIT 10;

SELECT
    'Null Emails' AS METRIC, COUNT(*) AS VALUE FROM ANALYTICS.CUSTOMERS WHERE EMAIL IS NULL
UNION ALL SELECT 'Null Phones', COUNT(*) FROM ANALYTICS.CUSTOMERS WHERE PHONE IS NULL
UNION ALL SELECT 'Duplicate Names', COUNT(*) FROM ANALYTICS.CUSTOMERS WHERE CUSTOMER_ID LIKE 'CUST-D%';

-- ============================================================
-- 4. AGENTS - Sample & Distribution
-- ============================================================
SELECT * FROM ANALYTICS.AGENTS LIMIT 10;

SELECT REGION, COUNT(*) AS CNT, ROUND(AVG(PERFORMANCE_RATING), 2) AS AVG_RATING
FROM ANALYTICS.AGENTS GROUP BY REGION ORDER BY CNT DESC;

SELECT SPECIALIZATION, COUNT(*) AS CNT FROM ANALYTICS.AGENTS GROUP BY SPECIALIZATION ORDER BY CNT DESC;

SELECT STATUS, COUNT(*) AS CNT FROM ANALYTICS.AGENTS GROUP BY STATUS;

-- Low performers with high policy counts (injected anomaly)
SELECT AGENT_ID, AGENT_NAME, REGION, PERFORMANCE_RATING, ACTIVE_POLICIES_COUNT
FROM ANALYTICS.AGENTS
WHERE PERFORMANCE_RATING < 2.0 AND ACTIVE_POLICIES_COUNT > 75
ORDER BY PERFORMANCE_RATING;

-- ============================================================
-- 5. POLICIES - Sample & Distribution
-- ============================================================
SELECT * FROM ANALYTICS.POLICIES LIMIT 10;

SELECT POLICY_TYPE, COUNT(*) AS CNT, ROUND(AVG(PREMIUM_AMOUNT), 2) AS AVG_PREMIUM,
       ROUND(AVG(COVERAGE_AMOUNT), 0) AS AVG_COVERAGE
FROM ANALYTICS.POLICIES GROUP BY POLICY_TYPE ORDER BY CNT DESC;

SELECT PLAN_TIER, COUNT(*) AS CNT, ROUND(AVG(DEDUCTIBLE), 2) AS AVG_DEDUCTIBLE
FROM ANALYTICS.POLICIES GROUP BY PLAN_TIER ORDER BY CNT DESC;

SELECT STATUS, COUNT(*) AS CNT FROM ANALYTICS.POLICIES GROUP BY STATUS ORDER BY CNT DESC;

SELECT RENEWAL_STATUS, COUNT(*) AS CNT FROM ANALYTICS.POLICIES GROUP BY RENEWAL_STATUS ORDER BY CNT DESC;

-- Premium outliers (injected)
SELECT POLICY_ID, POLICY_TYPE, PREMIUM_AMOUNT, COVERAGE_AMOUNT
FROM ANALYTICS.POLICIES WHERE PREMIUM_AMOUNT > 10000 ORDER BY PREMIUM_AMOUNT DESC;

-- ============================================================
-- 6. CLAIMS - Sample & Distribution
-- ============================================================
SELECT * FROM ANALYTICS.CLAIMS LIMIT 10;

SELECT CLAIM_TYPE, COUNT(*) AS CNT, ROUND(AVG(CLAIM_AMOUNT), 2) AS AVG_AMOUNT,
       ROUND(AVG(FRAUD_SCORE), 2) AS AVG_FRAUD
FROM ANALYTICS.CLAIMS GROUP BY CLAIM_TYPE ORDER BY CNT DESC;

SELECT STATUS, COUNT(*) AS CNT FROM ANALYTICS.CLAIMS GROUP BY STATUS ORDER BY CNT DESC;

-- Seasonal distribution (monthly)
SELECT DATE_TRUNC('month', CLAIM_DATE) AS MONTH, COUNT(*) AS CLAIMS
FROM ANALYTICS.CLAIMS GROUP BY MONTH ORDER BY MONTH;

-- Fraud score distribution
SELECT
    CASE
        WHEN FRAUD_SCORE < 20 THEN '0-20 (Low)'
        WHEN FRAUD_SCORE < 40 THEN '20-40 (Normal)'
        WHEN FRAUD_SCORE < 60 THEN '40-60 (Elevated)'
        WHEN FRAUD_SCORE < 80 THEN '60-80 (High)'
        ELSE '80-100 (Critical)'
    END AS FRAUD_BAND,
    COUNT(*) AS CNT
FROM ANALYTICS.CLAIMS GROUP BY FRAUD_BAND ORDER BY FRAUD_BAND;

-- Resolution days distribution
SELECT
    CASE
        WHEN RESOLUTION_DAYS <= 30 THEN '0-30 days'
        WHEN RESOLUTION_DAYS <= 90 THEN '31-90 days'
        WHEN RESOLUTION_DAYS <= 180 THEN '91-180 days'
        ELSE '180+ days'
    END AS RESOLUTION_BAND,
    COUNT(*) AS CNT, ROUND(AVG(FRICTION_SCORE), 2) AS AVG_FRICTION
FROM ANALYTICS.CLAIMS GROUP BY RESOLUTION_BAND ORDER BY RESOLUTION_BAND;

-- Hurricane claims (injected seasonal spike)
SELECT CAUSE_OF_LOSS, COUNT(*) AS CNT, ROUND(AVG(CLAIM_AMOUNT), 2) AS AVG_AMT
FROM ANALYTICS.CLAIMS
WHERE CAUSE_OF_LOSS = 'Hurricane/Tropical Storm'
GROUP BY CAUSE_OF_LOSS;

-- ============================================================
-- 7. BILLING - Sample & Distribution
-- ============================================================
SELECT * FROM ANALYTICS.BILLING LIMIT 10;

SELECT PAYMENT_STATUS, COUNT(*) AS CNT,
       ROUND(SUM(OUTSTANDING_BALANCE), 2) AS TOTAL_OUTSTANDING,
       ROUND(SUM(LATE_FEE), 2) AS TOTAL_LATE_FEES
FROM ANALYTICS.BILLING GROUP BY PAYMENT_STATUS ORDER BY CNT DESC;

SELECT PAYMENT_METHOD, COUNT(*) AS CNT
FROM ANALYTICS.BILLING WHERE PAYMENT_METHOD IS NOT NULL GROUP BY PAYMENT_METHOD ORDER BY CNT DESC;

-- Delinquency rate by month
SELECT DATE_TRUNC('month', INVOICE_DATE) AS MONTH,
       COUNT(*) AS TOTAL_INVOICES,
       SUM(CASE WHEN PAYMENT_STATUS = 'Overdue' THEN 1 ELSE 0 END) AS OVERDUE,
       ROUND(SUM(CASE WHEN PAYMENT_STATUS = 'Overdue' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS OVERDUE_PCT
FROM ANALYTICS.BILLING GROUP BY MONTH ORDER BY MONTH DESC LIMIT 12;

-- ============================================================
-- 8. AT_RISK_POLICIES - Sample & Distribution
-- ============================================================
SELECT * FROM ANALYTICS.AT_RISK_POLICIES LIMIT 10;

SELECT RISK_CATEGORY, COUNT(*) AS CNT,
       ROUND(AVG(CHURN_PROBABILITY), 4) AS AVG_CHURN_PROB,
       ROUND(SUM(REVENUE_AT_RISK), 2) AS TOTAL_REVENUE_AT_RISK
FROM ANALYTICS.AT_RISK_POLICIES GROUP BY RISK_CATEGORY ORDER BY TOTAL_REVENUE_AT_RISK DESC;

SELECT RETENTION_ACTION, COUNT(*) AS CNT
FROM ANALYTICS.AT_RISK_POLICIES GROUP BY RETENTION_ACTION ORDER BY CNT DESC;

-- High churn + high revenue at risk (top 10)
SELECT RISK_ID, POLICY_ID, CUSTOMER_ID, CHURN_PROBABILITY, REVENUE_AT_RISK, MISSED_PAYMENTS_COUNT, NPS_SCORE
FROM ANALYTICS.AT_RISK_POLICIES
ORDER BY CHURN_PROBABILITY * REVENUE_AT_RISK DESC
LIMIT 10;

-- ============================================================
-- 9. POLICY_DOCUMENTS - Sample & Content Preview
-- ============================================================
SELECT DOCUMENT_ID, POLICY_ID, DOCUMENT_TYPE, TITLE, LEFT(CONTENT, 200) AS CONTENT_PREVIEW,
       SUMMARY, EFFECTIVE_DATE, VERSION, FILE_FORMAT
FROM DOCUMENTS.POLICY_DOCUMENTS LIMIT 10;

SELECT DOCUMENT_TYPE, COUNT(*) AS CNT FROM DOCUMENTS.POLICY_DOCUMENTS GROUP BY DOCUMENT_TYPE ORDER BY CNT DESC;

-- ============================================================
-- 10. DOCUMENT_CHUNKS - RAG Layer Preview
-- ============================================================
SELECT CHUNK_ID, DOCUMENT_ID, CHUNK_INDEX, LEFT(CHUNK_TEXT, 150) AS CHUNK_PREVIEW, TOKEN_COUNT, EMBEDDING_MODEL
FROM DOCUMENTS.DOCUMENT_CHUNKS LIMIT 10;

SELECT EMBEDDING_MODEL, COUNT(*) AS CNT, ROUND(AVG(TOKEN_COUNT)) AS AVG_TOKENS
FROM DOCUMENTS.DOCUMENT_CHUNKS GROUP BY EMBEDDING_MODEL;

-- ============================================================
-- 11. DQ_RULES - All 50 Rules Overview
-- ============================================================
SELECT * FROM DATA_QUALITY.DQ_RULES ORDER BY RULE_ID;

SELECT RULE_TYPE, COUNT(*) AS CNT FROM DATA_QUALITY.DQ_RULES GROUP BY RULE_TYPE ORDER BY CNT DESC;

SELECT TARGET_TABLE, COUNT(*) AS RULES_COUNT FROM DATA_QUALITY.DQ_RULES GROUP BY TARGET_TABLE ORDER BY RULES_COUNT DESC;

SELECT SEVERITY, COUNT(*) AS CNT FROM DATA_QUALITY.DQ_RULES GROUP BY SEVERITY ORDER BY CNT DESC;

-- ============================================================
-- 12. DQ_RESULTS - Execution History
-- ============================================================
SELECT * FROM DATA_QUALITY.DQ_RESULTS ORDER BY RUN_DATE DESC LIMIT 10;

SELECT STATUS, COUNT(*) AS CNT FROM DATA_QUALITY.DQ_RESULTS GROUP BY STATUS ORDER BY CNT DESC;

-- Rules that fail most often
SELECT r.RULE_NAME, r.TARGET_TABLE, r.SEVERITY, COUNT(*) AS FAIL_COUNT
FROM DATA_QUALITY.DQ_RESULTS res
JOIN DATA_QUALITY.DQ_RULES r ON res.RULE_ID = r.RULE_ID
WHERE res.STATUS = 'Fail'
GROUP BY r.RULE_NAME, r.TARGET_TABLE, r.SEVERITY
ORDER BY FAIL_COUNT DESC
LIMIT 10;

-- ============================================================
-- 13. DQ_SCORES - Table Health Over Time
-- ============================================================
SELECT * FROM DATA_QUALITY.DQ_SCORES ORDER BY SCORE_DATE DESC LIMIT 10;

-- Latest score per table
SELECT TABLE_NAME, OVERALL_SCORE, COMPLETENESS_SCORE, VALIDITY_SCORE, TIMELINESS_SCORE, TREND, SCORE_DATE
FROM DATA_QUALITY.DQ_SCORES
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_NAME ORDER BY SCORE_DATE DESC) = 1
ORDER BY OVERALL_SCORE;

-- ============================================================
-- 14. DQ_COLUMN_HEALTH - Column-Level Issues
-- ============================================================
SELECT * FROM DATA_QUALITY.DQ_COLUMN_HEALTH ORDER BY CHECK_DATE DESC LIMIT 10;

-- Unhealthiest columns
SELECT TABLE_NAME, COLUMN_NAME, ROUND(AVG(HEALTH_SCORE), 2) AS AVG_HEALTH,
       ROUND(AVG(NULL_RATE), 2) AS AVG_NULL_RATE,
       ROUND(AVG(OUTLIER_RATE), 2) AS AVG_OUTLIER_RATE,
       MAX(STATUS) AS WORST_STATUS
FROM DATA_QUALITY.DQ_COLUMN_HEALTH
GROUP BY TABLE_NAME, COLUMN_NAME
ORDER BY AVG_HEALTH
LIMIT 15;

-- ============================================================
-- 15. CROSS-TABLE ANALYTICS (Join Queries)
-- ============================================================

-- Customer 360: Full customer view with policies, claims, billing
SELECT
    c.CUSTOMER_ID, c.FIRST_NAME || ' ' || c.LAST_NAME AS FULL_NAME,
    c.RISK_TIER, c.CREDIT_SCORE, c.SEGMENT,
    COUNT(DISTINCT p.POLICY_ID) AS POLICY_COUNT,
    COUNT(DISTINCT cl.CLAIM_ID) AS CLAIM_COUNT,
    ROUND(SUM(DISTINCT p.PREMIUM_AMOUNT), 2) AS TOTAL_PREMIUMS,
    ROUND(COALESCE(SUM(b.OUTSTANDING_BALANCE), 0), 2) AS TOTAL_OUTSTANDING
FROM ANALYTICS.CUSTOMERS c
LEFT JOIN ANALYTICS.POLICIES p ON c.CUSTOMER_ID = p.CUSTOMER_ID
LEFT JOIN ANALYTICS.CLAIMS cl ON c.CUSTOMER_ID = cl.CUSTOMER_ID
LEFT JOIN ANALYTICS.BILLING b ON c.CUSTOMER_ID = b.CUSTOMER_ID AND b.PAYMENT_STATUS = 'Overdue'
GROUP BY c.CUSTOMER_ID, FULL_NAME, c.RISK_TIER, c.CREDIT_SCORE, c.SEGMENT
ORDER BY TOTAL_OUTSTANDING DESC
LIMIT 20;

-- Agent Performance: Claims + Policies + Risk
SELECT
    a.AGENT_ID, a.AGENT_NAME, a.REGION, a.SPECIALIZATION, a.PERFORMANCE_RATING,
    COUNT(DISTINCT p.POLICY_ID) AS POLICIES_MANAGED,
    COUNT(DISTINCT cl.CLAIM_ID) AS CLAIMS_ON_POLICIES,
    COUNT(DISTINCT ar.RISK_ID) AS AT_RISK_COUNT,
    ROUND(SUM(ar.REVENUE_AT_RISK), 2) AS TOTAL_REVENUE_AT_RISK
FROM ANALYTICS.AGENTS a
LEFT JOIN ANALYTICS.POLICIES p ON a.AGENT_ID = p.AGENT_ID
LEFT JOIN ANALYTICS.CLAIMS cl ON p.POLICY_ID = cl.POLICY_ID
LEFT JOIN ANALYTICS.AT_RISK_POLICIES ar ON p.POLICY_ID = ar.POLICY_ID
GROUP BY a.AGENT_ID, a.AGENT_NAME, a.REGION, a.SPECIALIZATION, a.PERFORMANCE_RATING
ORDER BY TOTAL_REVENUE_AT_RISK DESC NULLS LAST
LIMIT 20;

-- Claims by Region (for the "North Region spike" demo)
SELECT
    a.REGION,
    DATE_TRUNC('month', cl.CLAIM_DATE) AS MONTH,
    COUNT(*) AS CLAIM_COUNT,
    ROUND(SUM(cl.CLAIM_AMOUNT), 2) AS TOTAL_CLAIMED,
    ROUND(AVG(cl.FRAUD_SCORE), 2) AS AVG_FRAUD_SCORE
FROM ANALYTICS.CLAIMS cl
JOIN ANALYTICS.POLICIES p ON cl.POLICY_ID = p.POLICY_ID
JOIN ANALYTICS.AGENTS a ON p.AGENT_ID = a.AGENT_ID
WHERE cl.CLAIM_DATE >= '2024-01-01'
GROUP BY a.REGION, MONTH
ORDER BY a.REGION, MONTH;

-- Revenue at Risk by Policy Type
SELECT
    p.POLICY_TYPE,
    COUNT(*) AS AT_RISK_COUNT,
    ROUND(SUM(ar.REVENUE_AT_RISK), 2) AS TOTAL_REVENUE_AT_RISK,
    ROUND(AVG(ar.CHURN_PROBABILITY), 4) AS AVG_CHURN_PROB,
    ROUND(AVG(ar.MISSED_PAYMENTS_COUNT), 1) AS AVG_MISSED_PAYMENTS
FROM ANALYTICS.AT_RISK_POLICIES ar
JOIN ANALYTICS.POLICIES p ON ar.POLICY_ID = p.POLICY_ID
GROUP BY p.POLICY_TYPE
ORDER BY TOTAL_REVENUE_AT_RISK DESC;
