-- ============================================================
-- INSURANCE AI HUB (E.D.I.E.) - Schema Evolution
-- Phase 9b: Bridge from original DDL (02_tables.sql) to current state
-- Run AFTER 07_inject_issues.sql, BEFORE 10_close_kpi_gaps.sql
-- ============================================================
--
-- This script adds ~50 columns across 11 tables, renames 3 columns,
-- and backfills all with realistic data. It transforms the original
-- schema (created by 02_tables.sql and populated by 03-07) into the
-- current production schema.
--
-- ============================================================

USE DATABASE INSURANCE_AI_HUB;
USE WAREHOUSE INSURANCE_AI_HUB_WH;

-- ############################################################################
-- 1. CUSTOMERS — Add 5 columns
-- ############################################################################
USE SCHEMA ANALYTICS;

ALTER TABLE CUSTOMERS ADD COLUMN IF NOT EXISTS SALESFORCE_ACCOUNT_ID VARCHAR(20);
ALTER TABLE CUSTOMERS ADD COLUMN IF NOT EXISTS PREFERRED_CONTACT_METHOD VARCHAR(10);
ALTER TABLE CUSTOMERS ADD COLUMN IF NOT EXISTS HOUSEHOLD_ID VARCHAR(20);
ALTER TABLE CUSTOMERS ADD COLUMN IF NOT EXISTS LIFE_EVENT_FLAG VARCHAR(20);
ALTER TABLE CUSTOMERS ADD COLUMN IF NOT EXISTS ANNUAL_INCOME_RANGE VARCHAR(15);

UPDATE CUSTOMERS SET
    SALESFORCE_ACCOUNT_ID = 'SF-' || LPAD(SUBSTR(CUSTOMER_ID, 6), 7, '0'),
    PREFERRED_CONTACT_METHOD = CASE MOD(ABS(HASH(CUSTOMER_ID || 'pcm')), 4)
        WHEN 0 THEN 'Email' WHEN 1 THEN 'Phone' WHEN 2 THEN 'SMS' ELSE 'Mail' END,
    HOUSEHOLD_ID = 'HH-' || LPAD((MOD(ABS(HASH(CUSTOMER_ID || 'hh')), 3000) + 1)::VARCHAR, 5, '0'),
    LIFE_EVENT_FLAG = CASE MOD(ABS(HASH(CUSTOMER_ID || 'le')), 10)
        WHEN 0 THEN 'Marriage' WHEN 1 THEN 'NewHome' WHEN 2 THEN 'NewChild'
        WHEN 3 THEN 'Retirement' WHEN 4 THEN 'Relocation' ELSE 'None' END,
    ANNUAL_INCOME_RANGE = CASE
        WHEN CREDIT_SCORE >= 750 THEN CASE MOD(ABS(HASH(CUSTOMER_ID || 'inc')), 3)
            WHEN 0 THEN '100K-150K' WHEN 1 THEN '150K-200K' ELSE '200K+' END
        WHEN CREDIT_SCORE >= 650 THEN CASE MOD(ABS(HASH(CUSTOMER_ID || 'inc')), 3)
            WHEN 0 THEN '75K-100K' WHEN 1 THEN '100K-150K' ELSE '50K-75K' END
        WHEN CREDIT_SCORE >= 550 THEN CASE MOD(ABS(HASH(CUSTOMER_ID || 'inc')), 2)
            WHEN 0 THEN '50K-75K' ELSE '35K-50K' END
        ELSE CASE MOD(ABS(HASH(CUSTOMER_ID || 'inc')), 2)
            WHEN 0 THEN '25K-35K' ELSE 'Under 25K' END
    END
WHERE SALESFORCE_ACCOUNT_ID IS NULL;


-- ############################################################################
-- 2. AGENTS — Add 7 columns (APPLICATION_DATE handled in 10_close_kpi_gaps)
-- ############################################################################

ALTER TABLE AGENTS ADD COLUMN IF NOT EXISTS AGENCY_NAME VARCHAR(100);
ALTER TABLE AGENTS ADD COLUMN IF NOT EXISTS PRODUCER_CODE VARCHAR(20);
ALTER TABLE AGENTS ADD COLUMN IF NOT EXISTS COMMISSION_RATE NUMBER(4,3);
ALTER TABLE AGENTS ADD COLUMN IF NOT EXISTS TOTAL_PREMIUM_BOOK NUMBER(14,2);
ALTER TABLE AGENTS ADD COLUMN IF NOT EXISTS RETENTION_RATE NUMBER(4,3);
ALTER TABLE AGENTS ADD COLUMN IF NOT EXISTS NPS_SCORE NUMBER(3,0);
ALTER TABLE AGENTS ADD COLUMN IF NOT EXISTS APPOINTMENT_STATUS VARCHAR(15);

UPDATE AGENTS SET
    AGENCY_NAME = CASE MOD(ABS(HASH(AGENT_ID || 'ag')), 12)
        WHEN 0 THEN 'Pinnacle Insurance Group'
        WHEN 1 THEN 'Heartland Risk Advisors'
        WHEN 2 THEN 'Coastal Shield Insurance'
        WHEN 3 THEN 'Summit Financial Partners'
        WHEN 4 THEN 'Liberty Star Agency'
        WHEN 5 THEN 'Guardian Oak Insurance'
        WHEN 6 THEN 'Evergreen Risk Solutions'
        WHEN 7 THEN 'Atlas Coverage Group'
        WHEN 8 THEN 'Beacon Insurance Services'
        WHEN 9 THEN 'Cornerstone Risk Partners'
        WHEN 10 THEN 'Meridian Insurance Agency'
        ELSE 'Vanguard Protection Group'
    END,
    PRODUCER_CODE = 'PC-' || LPAD(SUBSTR(AGENT_ID, 5), 5, '0'),
    COMMISSION_RATE = ROUND(CASE SPECIALIZATION
        WHEN 'Commercial' THEN 0.08 + MOD(ABS(HASH(AGENT_ID || 'cr')), 50) / 1000.0
        WHEN 'Life' THEN 0.10 + MOD(ABS(HASH(AGENT_ID || 'cr')), 50) / 1000.0
        WHEN 'Health' THEN 0.06 + MOD(ABS(HASH(AGENT_ID || 'cr')), 40) / 1000.0
        WHEN 'Home' THEN 0.07 + MOD(ABS(HASH(AGENT_ID || 'cr')), 45) / 1000.0
        ELSE 0.05 + MOD(ABS(HASH(AGENT_ID || 'cr')), 50) / 1000.0
    END, 3),
    TOTAL_PREMIUM_BOOK = ROUND(ACTIVE_POLICIES_COUNT *
        CASE SPECIALIZATION
            WHEN 'Commercial' THEN 2500 WHEN 'Home' THEN 350 WHEN 'Health' THEN 500
            WHEN 'Life' THEN 200 ELSE 300
        END * (0.8 + MOD(ABS(HASH(AGENT_ID || 'tpb')), 40) / 100.0), 2),
    RETENTION_RATE = ROUND(CASE
        WHEN PERFORMANCE_RATING >= 4.0 THEN 0.88 + MOD(ABS(HASH(AGENT_ID || 'rr')), 100) / 1000.0
        WHEN PERFORMANCE_RATING >= 3.0 THEN 0.78 + MOD(ABS(HASH(AGENT_ID || 'rr')), 100) / 1000.0
        WHEN PERFORMANCE_RATING >= 2.0 THEN 0.68 + MOD(ABS(HASH(AGENT_ID || 'rr')), 100) / 1000.0
        ELSE 0.55 + MOD(ABS(HASH(AGENT_ID || 'rr')), 150) / 1000.0
    END, 3),
    NPS_SCORE = CASE
        WHEN PERFORMANCE_RATING >= 4.0 THEN 40 + MOD(ABS(HASH(AGENT_ID || 'nps')), 50)
        WHEN PERFORMANCE_RATING >= 3.0 THEN 10 + MOD(ABS(HASH(AGENT_ID || 'nps')), 40)
        WHEN PERFORMANCE_RATING >= 2.0 THEN -10 + MOD(ABS(HASH(AGENT_ID || 'nps')), 30)
        ELSE -20 + MOD(ABS(HASH(AGENT_ID || 'nps')), 20)
    END,
    APPOINTMENT_STATUS = CASE
        WHEN STATUS = 'Inactive' THEN 'Terminated'
        WHEN PERFORMANCE_RATING < 2.0 THEN 'Probationary'
        ELSE 'Active'
    END
WHERE AGENCY_NAME IS NULL;


-- ############################################################################
-- 3. POLICIES — Rename 3 columns, add 7 new columns
-- ############################################################################

-- Renames
ALTER TABLE POLICIES RENAME COLUMN PLAN_TIER TO COVERAGE_TIER;
ALTER TABLE POLICIES RENAME COLUMN START_DATE TO EFFECTIVE_DATE;
ALTER TABLE POLICIES RENAME COLUMN END_DATE TO EXPIRATION_DATE;

-- Widen types for compatibility
ALTER TABLE POLICIES ALTER COLUMN POLICY_TYPE SET DATA TYPE VARCHAR(30);
ALTER TABLE POLICIES ALTER COLUMN COVERAGE_TIER SET DATA TYPE VARCHAR(15);

-- Add new columns
ALTER TABLE POLICIES ADD COLUMN IF NOT EXISTS POLICY_NUMBER VARCHAR(30);
ALTER TABLE POLICIES ADD COLUMN IF NOT EXISTS LINE_OF_BUSINESS VARCHAR(40);
ALTER TABLE POLICIES ADD COLUMN IF NOT EXISTS BOUND_DATE DATE;
ALTER TABLE POLICIES ADD COLUMN IF NOT EXISTS POLICY_TERM_MONTHS NUMBER(3,0);
ALTER TABLE POLICIES ADD COLUMN IF NOT EXISTS ISSUING_STATE VARCHAR(2);
ALTER TABLE POLICIES ADD COLUMN IF NOT EXISTS ENDORSEMENT_TYPE VARCHAR(30);
ALTER TABLE POLICIES ADD COLUMN IF NOT EXISTS EXPENSE_AMOUNT NUMBER(12,2);

UPDATE POLICIES SET
    POLICY_NUMBER = 'PN-' || REPLACE(POLICY_ID, 'POL-', '') || '-' ||
        LPAD(MOD(ABS(HASH(POLICY_ID || 'pn')), 99)::VARCHAR, 2, '0'),
    LINE_OF_BUSINESS = CASE POLICY_TYPE
        WHEN 'Auto' THEN 'Personal Auto'
        WHEN 'Home' THEN 'Homeowners'
        WHEN 'Life' THEN 'Individual Life'
        WHEN 'Health' THEN 'Group Health'
        WHEN 'Commercial' THEN 'Commercial Lines'
        ELSE 'Specialty'
    END,
    BOUND_DATE = DATEADD('day', -(1 + MOD(ABS(HASH(POLICY_ID || 'bd')), 14)), EFFECTIVE_DATE),
    POLICY_TERM_MONTHS = ROUND(DATEDIFF('month', EFFECTIVE_DATE, EXPIRATION_DATE)),
    ISSUING_STATE = (SELECT c.STATE FROM CUSTOMERS c WHERE c.CUSTOMER_ID = POLICIES.CUSTOMER_ID LIMIT 1),
    ENDORSEMENT_TYPE = CASE
        WHEN MOD(ABS(HASH(POLICY_ID || 'et')), 100) < 15 THEN 'Rider'
        WHEN MOD(ABS(HASH(POLICY_ID || 'et')), 100) < 25 THEN 'AdditionalInsured'
        WHEN MOD(ABS(HASH(POLICY_ID || 'et')), 100) < 32 THEN 'Waiver'
        WHEN MOD(ABS(HASH(POLICY_ID || 'et')), 100) < 38 THEN 'CoverageExtension'
        ELSE NULL
    END,
    EXPENSE_AMOUNT = ROUND(PREMIUM_AMOUNT * (0.15 + MOD(ABS(HASH(POLICY_ID || 'ea')), 200) / 1000.0), 2)
WHERE POLICY_NUMBER IS NULL;

-- Fix any NULL ISSUING_STATE from the subquery
UPDATE POLICIES SET ISSUING_STATE = 'CA' WHERE ISSUING_STATE IS NULL;


-- ############################################################################
-- 4. CLAIMS — Add 9 columns (ESCALATION_FLAG handled in 10_close_kpi_gaps)
-- ############################################################################

ALTER TABLE CLAIMS ALTER COLUMN STATUS SET DATA TYPE VARCHAR(20);
ALTER TABLE CLAIMS ALTER COLUMN CAUSE_OF_LOSS SET DATA TYPE VARCHAR(30);

ALTER TABLE CLAIMS ADD COLUMN IF NOT EXISTS LOSS_DATE DATE;
ALTER TABLE CLAIMS ADD COLUMN IF NOT EXISTS FNOL_DATE DATE;
ALTER TABLE CLAIMS ADD COLUMN IF NOT EXISTS FNOL_CHANNEL VARCHAR(15);
ALTER TABLE CLAIMS ADD COLUMN IF NOT EXISTS REPORTED_BY VARCHAR(15);
ALTER TABLE CLAIMS ADD COLUMN IF NOT EXISTS RESERVE_AMOUNT NUMBER(12,2);
ALTER TABLE CLAIMS ADD COLUMN IF NOT EXISTS PAID_AMOUNT NUMBER(12,2) DEFAULT 0;
ALTER TABLE CLAIMS ADD COLUMN IF NOT EXISTS RECOVERY_AMOUNT NUMBER(12,2) DEFAULT 0;
ALTER TABLE CLAIMS ADD COLUMN IF NOT EXISTS LITIGATION_FLAG BOOLEAN DEFAULT FALSE;
ALTER TABLE CLAIMS ADD COLUMN IF NOT EXISTS CATASTROPHE_CODE VARCHAR(20);

UPDATE CLAIMS SET
    LOSS_DATE = DATEADD('day', -(MOD(ABS(HASH(CLAIM_ID || 'ld')), 8)), CLAIM_DATE),
    FNOL_DATE = DATEADD('day', MOD(ABS(HASH(CLAIM_ID || 'fn')), 4), CLAIM_DATE),
    FNOL_CHANNEL = CASE MOD(ABS(HASH(CLAIM_ID || 'fc')), 5)
        WHEN 0 THEN 'Phone' WHEN 1 THEN 'Web' WHEN 2 THEN 'Email'
        WHEN 3 THEN 'Agent' ELSE 'MobileApp' END,
    REPORTED_BY = CASE MOD(ABS(HASH(CLAIM_ID || 'rb')), 5)
        WHEN 0 THEN 'Policyholder' WHEN 1 THEN 'Policyholder' WHEN 2 THEN 'Agent'
        WHEN 3 THEN 'ThirdParty' ELSE 'Policyholder' END,
    RESERVE_AMOUNT = CASE
        WHEN STATUS IN ('Open','UnderInvestigation') THEN ROUND(CLAIM_AMOUNT * (0.8 + MOD(ABS(HASH(CLAIM_ID || 'ra')), 40) / 100.0), 2)
        ELSE APPROVED_AMOUNT
    END,
    PAID_AMOUNT = CASE
        WHEN STATUS IN ('Closed','Approved','PartiallyPaid') AND APPROVED_AMOUNT IS NOT NULL
        THEN ROUND(APPROVED_AMOUNT * (0.7 + MOD(ABS(HASH(CLAIM_ID || 'pa')), 30) / 100.0), 2)
        ELSE 0
    END,
    RECOVERY_AMOUNT = CASE
        WHEN STATUS IN ('Closed','Subrogation') AND MOD(ABS(HASH(CLAIM_ID || 'rc')), 100) < 15
        THEN ROUND(CLAIM_AMOUNT * (0.05 + MOD(ABS(HASH(CLAIM_ID || 'rc2')), 20) / 100.0), 2)
        ELSE 0
    END,
    LITIGATION_FLAG = CASE
        WHEN MOD(ABS(HASH(CLAIM_ID || 'lit')), 100) < 5 THEN TRUE
        WHEN CLAIM_AMOUNT > 12000 AND MOD(ABS(HASH(CLAIM_ID || 'lit2')), 100) < 15 THEN TRUE
        ELSE FALSE
    END,
    CATASTROPHE_CODE = CASE
        WHEN CAUSE_OF_LOSS IN ('Hurricane/Tropical Storm','Natural Disaster','Weather Event')
        THEN 'CAT-' || LPAD(MOD(ABS(HASH(CLAIM_ID || 'cat')), 20 + 1)::VARCHAR, 3, '0')
        ELSE NULL
    END
WHERE LOSS_DATE IS NULL;


-- ############################################################################
-- 5. BILLING — Add 6 columns
-- ############################################################################

ALTER TABLE BILLING ALTER COLUMN PAYMENT_STATUS SET DATA TYPE VARCHAR(20);

ALTER TABLE BILLING ADD COLUMN IF NOT EXISTS BILLING_PLAN VARCHAR(15);
ALTER TABLE BILLING ADD COLUMN IF NOT EXISTS INSTALLMENT_NUMBER NUMBER(3,0);
ALTER TABLE BILLING ADD COLUMN IF NOT EXISTS TOTAL_INSTALLMENTS NUMBER(3,0);
ALTER TABLE BILLING ADD COLUMN IF NOT EXISTS GRACE_PERIOD_END DATE;
ALTER TABLE BILLING ADD COLUMN IF NOT EXISTS TRANSACTION_REF VARCHAR(30);
ALTER TABLE BILLING ADD COLUMN IF NOT EXISTS CANCELLATION_DATE DATE;

UPDATE BILLING SET
    BILLING_PLAN = CASE MOD(ABS(HASH(INVOICE_ID || 'bp')), 4)
        WHEN 0 THEN 'Monthly' WHEN 1 THEN 'Monthly' WHEN 2 THEN 'Quarterly' ELSE 'Annual' END,
    INSTALLMENT_NUMBER = MOD(ABS(HASH(INVOICE_ID || 'in')), 12) + 1,
    TOTAL_INSTALLMENTS = CASE MOD(ABS(HASH(INVOICE_ID || 'bp')), 4)
        WHEN 0 THEN 12 WHEN 1 THEN 12 WHEN 2 THEN 4 ELSE 1 END,
    GRACE_PERIOD_END = DATEADD('day', 15, DUE_DATE),
    TRANSACTION_REF = CASE
        WHEN PAYMENT_STATUS IN ('Paid','Partial') AND PAYMENT_DATE IS NOT NULL
        THEN 'TXN-' || LPAD(ABS(HASH(INVOICE_ID || 'txn'))::VARCHAR, 12, '0')
        ELSE NULL
    END,
    CANCELLATION_DATE = NULL
WHERE BILLING_PLAN IS NULL;

-- Remap old payment statuses to new values
UPDATE BILLING SET PAYMENT_STATUS = 'PastDue' WHERE PAYMENT_STATUS = 'Overdue';
UPDATE BILLING SET PAYMENT_STATUS = 'InGracePeriod'
WHERE PAYMENT_STATUS = 'Pending'
  AND MOD(ABS(HASH(INVOICE_ID || 'gp')), 100) < 30;
UPDATE BILLING SET PAYMENT_STATUS = 'Waived'
WHERE PAYMENT_STATUS = 'Paid'
  AND AMOUNT_DUE < 10
  AND MOD(ABS(HASH(INVOICE_ID || 'wv')), 100) < 5;
UPDATE BILLING SET PAYMENT_STATUS = 'Refunded'
WHERE PAYMENT_STATUS = 'Paid'
  AND MOD(ABS(HASH(INVOICE_ID || 'rf')), 100) < 2;
UPDATE BILLING SET PAYMENT_STATUS = 'SentToCollections'
WHERE PAYMENT_STATUS = 'PastDue'
  AND LATE_FEE > 50
  AND MOD(ABS(HASH(INVOICE_ID || 'sc')), 100) < 20;


-- ############################################################################
-- 6. AT_RISK_POLICIES — Add 5 columns
-- ############################################################################

ALTER TABLE AT_RISK_POLICIES ALTER COLUMN RISK_CATEGORY SET DATA TYPE VARCHAR(25);

ALTER TABLE AT_RISK_POLICIES ADD COLUMN IF NOT EXISTS CUSTOMER_LIFETIME_VALUE NUMBER(12,2);
ALTER TABLE AT_RISK_POLICIES ADD COLUMN IF NOT EXISTS COMPETITOR_QUOTE_FLAG BOOLEAN DEFAULT FALSE;
ALTER TABLE AT_RISK_POLICIES ADD COLUMN IF NOT EXISTS MODEL_VERSION VARCHAR(15);
ALTER TABLE AT_RISK_POLICIES ADD COLUMN IF NOT EXISTS SCORE_DATE DATE;
ALTER TABLE AT_RISK_POLICIES ADD COLUMN IF NOT EXISTS CAMPAIGN_ID VARCHAR(20);

UPDATE AT_RISK_POLICIES SET
    CUSTOMER_LIFETIME_VALUE = ROUND(REVENUE_AT_RISK * (2.5 + MOD(ABS(HASH(RISK_ID || 'ltv')), 50) / 10.0), 2),
    COMPETITOR_QUOTE_FLAG = CASE WHEN MOD(ABS(HASH(RISK_ID || 'cq')), 100) < 20 THEN TRUE ELSE FALSE END,
    MODEL_VERSION = CASE MOD(ABS(HASH(RISK_ID || 'mv')), 3)
        WHEN 0 THEN 'v2.1' WHEN 1 THEN 'v2.0' ELSE 'v1.9' END,
    SCORE_DATE = DATEADD('day', -(MOD(ABS(HASH(RISK_ID || 'sd')), 7)), SNAPSHOT_DATE),
    CAMPAIGN_ID = CASE
        WHEN MOD(ABS(HASH(RISK_ID || 'cmp')), 100) < 40
        THEN 'CMP-' || LPAD((MOD(ABS(HASH(RISK_ID || 'cmp2')), 20) + 1)::VARCHAR, 3, '0')
        ELSE NULL
    END
WHERE CUSTOMER_LIFETIME_VALUE IS NULL;

-- Remap risk categories to match current values
UPDATE AT_RISK_POLICIES SET RISK_CATEGORY = 'VoluntaryChurn' WHERE RISK_CATEGORY = 'Churn';
UPDATE AT_RISK_POLICIES SET RISK_CATEGORY = 'InvoluntaryChurn' WHERE RISK_CATEGORY = 'Payment Default';
UPDATE AT_RISK_POLICIES SET RISK_CATEGORY = CASE MOD(ABS(HASH(RISK_ID || 'rc')), 3)
    WHEN 0 THEN 'CompetitorSwitch' WHEN 1 THEN 'ServiceDissatisfaction' ELSE 'Underinsured' END
WHERE RISK_CATEGORY = 'Underinsured'
  AND MOD(ABS(HASH(RISK_ID || 'rc2')), 100) < 60;


-- ############################################################################
-- 7. POLICY_DOCUMENTS — Add 4 columns
-- ############################################################################
USE SCHEMA DOCUMENTS;

ALTER TABLE POLICY_DOCUMENTS ADD COLUMN IF NOT EXISTS SOURCE_SYSTEM VARCHAR(20);
ALTER TABLE POLICY_DOCUMENTS ADD COLUMN IF NOT EXISTS FILING_STATE VARCHAR(2);
ALTER TABLE POLICY_DOCUMENTS ADD COLUMN IF NOT EXISTS REGULATORY_APPROVAL_DATE DATE;
ALTER TABLE POLICY_DOCUMENTS ADD COLUMN IF NOT EXISTS FORM_NUMBER VARCHAR(20);

UPDATE POLICY_DOCUMENTS SET
    SOURCE_SYSTEM = CASE MOD(ABS(HASH(DOCUMENT_ID || 'ss')), 3)
        WHEN 0 THEN 'PolicyAdmin' WHEN 1 THEN 'DocGen' ELSE 'Legacy' END,
    FILING_STATE = (SELECT p.ISSUING_STATE FROM INSURANCE_AI_HUB.ANALYTICS.POLICIES p
                    WHERE p.POLICY_ID = POLICY_DOCUMENTS.POLICY_ID LIMIT 1),
    REGULATORY_APPROVAL_DATE = DATEADD('day', -(30 + MOD(ABS(HASH(DOCUMENT_ID || 'ra')), 150)), EFFECTIVE_DATE),
    FORM_NUMBER = 'FM-' || UPPER(LEFT(DOCUMENT_TYPE, 3)) || '-' ||
        LPAD(MOD(ABS(HASH(DOCUMENT_ID || 'fm')), 999)::VARCHAR, 3, '0')
WHERE SOURCE_SYSTEM IS NULL;

UPDATE POLICY_DOCUMENTS SET FILING_STATE = 'CA' WHERE FILING_STATE IS NULL;


-- ############################################################################
-- 8. DQ_RULES — Drop RULE_EXPRESSION, add 3 columns
-- ############################################################################
USE SCHEMA DATA_QUALITY;

ALTER TABLE DQ_RULES DROP COLUMN IF EXISTS RULE_EXPRESSION;
ALTER TABLE DQ_RULES ADD COLUMN IF NOT EXISTS SOURCE_SYSTEM VARCHAR(30);
ALTER TABLE DQ_RULES ADD COLUMN IF NOT EXISTS PIPELINE_NAME VARCHAR(50);
ALTER TABLE DQ_RULES ADD COLUMN IF NOT EXISTS OWNER VARCHAR(50);

UPDATE DQ_RULES SET
    SOURCE_SYSTEM = CASE MOD(ABS(HASH(RULE_ID || 'ss')), 3)
        WHEN 0 THEN 'PolicyAdmin' WHEN 1 THEN 'ClaimsSystem' ELSE 'BillingPlatform' END,
    PIPELINE_NAME = CASE TARGET_SCHEMA
        WHEN 'ANALYTICS' THEN 'analytics_dq_pipeline'
        ELSE 'documents_dq_pipeline'
    END,
    OWNER = CASE MOD(ABS(HASH(RULE_ID || 'ow')), 4)
        WHEN 0 THEN 'data_quality_team' WHEN 1 THEN 'data_engineering'
        WHEN 2 THEN 'analytics_ops' ELSE 'platform_team' END
WHERE SOURCE_SYSTEM IS NULL;


-- ############################################################################
-- 9. DQ_RESULTS — Add 2 columns
-- ############################################################################

ALTER TABLE DQ_RESULTS ADD COLUMN IF NOT EXISTS PIPELINE_RUN_ID VARCHAR(30);
ALTER TABLE DQ_RESULTS ADD COLUMN IF NOT EXISTS ANOMALY_SCORE NUMBER(4,3);

UPDATE DQ_RESULTS SET
    PIPELINE_RUN_ID = 'PRN-' || LPAD(ABS(HASH(RESULT_ID || 'prn'))::VARCHAR, 10, '0'),
    ANOMALY_SCORE = CASE
        WHEN STATUS = 'Fail' THEN ROUND(0.5 + MOD(ABS(HASH(RESULT_ID || 'as')), 500) / 1000.0, 3)
        WHEN STATUS = 'Warning' THEN ROUND(0.2 + MOD(ABS(HASH(RESULT_ID || 'as')), 300) / 1000.0, 3)
        ELSE ROUND(MOD(ABS(HASH(RESULT_ID || 'as')), 200) / 1000.0, 3)
    END
WHERE PIPELINE_RUN_ID IS NULL;


-- ############################################################################
-- 10. DQ_SCORES — Add 1 column
-- ############################################################################

ALTER TABLE DQ_SCORES ADD COLUMN IF NOT EXISTS SOURCE_SYSTEM VARCHAR(30);

UPDATE DQ_SCORES SET
    SOURCE_SYSTEM = CASE MOD(ABS(HASH(SCORE_ID || 'ss')), 3)
        WHEN 0 THEN 'PolicyAdmin' WHEN 1 THEN 'ClaimsSystem' ELSE 'BillingPlatform' END
WHERE SOURCE_SYSTEM IS NULL;


-- ############################################################################
-- 11. DQ_COLUMN_HEALTH — Add 1 column
-- ############################################################################

ALTER TABLE DQ_COLUMN_HEALTH ADD COLUMN IF NOT EXISTS FRESHNESS_HOURS NUMBER(6,1);

UPDATE DQ_COLUMN_HEALTH SET
    FRESHNESS_HOURS = CASE
        WHEN STATUS = 'Critical' THEN 48.0 + MOD(ABS(HASH(HEALTH_ID || 'fh')), 720) / 10.0
        WHEN STATUS = 'Warning' THEN 12.0 + MOD(ABS(HASH(HEALTH_ID || 'fh')), 360) / 10.0
        ELSE 0.5 + MOD(ABS(HASH(HEALTH_ID || 'fh')), 120) / 10.0
    END
WHERE FRESHNESS_HOURS IS NULL;


-- ############################################################################
-- VERIFICATION
-- ############################################################################

SELECT 'CUSTOMERS' AS TBL, COUNT(*) AS TOTAL,
    COUNT(SALESFORCE_ACCOUNT_ID) AS NEW_COLS_FILLED FROM ANALYTICS.CUSTOMERS
UNION ALL SELECT 'AGENTS', COUNT(*), COUNT(AGENCY_NAME) FROM ANALYTICS.AGENTS
UNION ALL SELECT 'POLICIES', COUNT(*), COUNT(POLICY_NUMBER) FROM ANALYTICS.POLICIES
UNION ALL SELECT 'CLAIMS', COUNT(*), COUNT(LOSS_DATE) FROM ANALYTICS.CLAIMS
UNION ALL SELECT 'BILLING', COUNT(*), COUNT(BILLING_PLAN) FROM ANALYTICS.BILLING
UNION ALL SELECT 'AT_RISK_POLICIES', COUNT(*), COUNT(CUSTOMER_LIFETIME_VALUE) FROM ANALYTICS.AT_RISK_POLICIES
UNION ALL SELECT 'POLICY_DOCUMENTS', COUNT(*), COUNT(SOURCE_SYSTEM) FROM DOCUMENTS.POLICY_DOCUMENTS
UNION ALL SELECT 'DQ_RULES', COUNT(*), COUNT(PIPELINE_NAME) FROM DATA_QUALITY.DQ_RULES
UNION ALL SELECT 'DQ_RESULTS', COUNT(*), COUNT(PIPELINE_RUN_ID) FROM DATA_QUALITY.DQ_RESULTS
UNION ALL SELECT 'DQ_SCORES', COUNT(*), COUNT(SOURCE_SYSTEM) FROM DATA_QUALITY.DQ_SCORES
UNION ALL SELECT 'DQ_COLUMN_HEALTH', COUNT(*), COUNT(FRESHNESS_HOURS) FROM DATA_QUALITY.DQ_COLUMN_HEALTH;
