-- Complete recursive DDL export for INSURANCE_AI_HUB database
-- Co-authored with CoCo

create or replace database INSURANCE_AI_HUB COMMENT='Insurance AI Hub (E.D.I.E.) - Enterprise Data & Intelligence Engine for insurance analytics, document intelligence, and data quality observability';

create or replace schema INSURANCE_AI_HUB.ADMIN;

create or replace schema INSURANCE_AI_HUB.ANALYTICS COMMENT='Core insurance analytics: customers, agents, policies, claims, billing, and retention risk';

create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.AGENTS (
	AGENT_ID VARCHAR(20) NOT NULL,
	AGENT_NAME VARCHAR(100) NOT NULL,
	AGENCY_NAME VARCHAR(100) NOT NULL,
	PRODUCER_CODE VARCHAR(20) NOT NULL,
	REGION VARCHAR(30) NOT NULL,
	STATE VARCHAR(2) NOT NULL,
	SPECIALIZATION VARCHAR(30) NOT NULL,
	LICENSE_NUMBER VARCHAR(20) NOT NULL,
	HIRE_DATE DATE NOT NULL,
	PERFORMANCE_RATING NUMBER(3,2) NOT NULL,
	COMMISSION_RATE NUMBER(4,3) NOT NULL,
	TOTAL_PREMIUM_BOOK NUMBER(14,2) NOT NULL,
	RETENTION_RATE NUMBER(4,3) NOT NULL,
	NPS_SCORE NUMBER(3,0),
	ACTIVE_POLICIES_COUNT NUMBER(38,0) NOT NULL,
	APPOINTMENT_STATUS VARCHAR(15) NOT NULL,
	STATUS VARCHAR(10) NOT NULL,
	APPLICATION_DATE DATE
);
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.APPLICATIONS (
	APPLICATION_ID VARCHAR(20) NOT NULL,
	CUSTOMER_ID VARCHAR(20),
	AGENT_ID VARCHAR(20),
	APPLICATION_DATE DATE NOT NULL,
	POLICY_TYPE VARCHAR(20) NOT NULL,
	REQUESTED_COVERAGE NUMBER(14,2) NOT NULL,
	REQUESTED_PREMIUM NUMBER(12,2) NOT NULL,
	RISK_SCORE NUMBER(5,2),
	UNDERWRITING_DECISION VARCHAR(20) NOT NULL,
	DECLINE_REASON VARCHAR(100),
	QUOTE_AMOUNT NUMBER(12,2),
	QUOTE_DATE DATE,
	BOUND_DATE DATE,
	POLICY_ID VARCHAR(20),
	STATUS VARCHAR(20) NOT NULL,
	CREATED_AT TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	constraint PK_APPLICATIONS primary key (APPLICATION_ID)
)COMMENT='Policy applications with underwriting decisions, quotes, and bind outcomes for conversion tracking'
;
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.AT_RISK_POLICIES (
	RISK_ID VARCHAR(20) NOT NULL,
	POLICY_ID VARCHAR(20) NOT NULL,
	CUSTOMER_ID VARCHAR(20) NOT NULL,
	RISK_CATEGORY VARCHAR(25) NOT NULL,
	CHURN_PROBABILITY NUMBER(5,4) NOT NULL,
	REVENUE_AT_RISK NUMBER(12,2) NOT NULL,
	CUSTOMER_LIFETIME_VALUE NUMBER(12,2) NOT NULL,
	DAYS_UNTIL_RENEWAL NUMBER(38,0) NOT NULL,
	MISSED_PAYMENTS_COUNT NUMBER(38,0) NOT NULL DEFAULT 0,
	CLAIM_FREQUENCY NUMBER(38,0) NOT NULL DEFAULT 0,
	NPS_SCORE NUMBER(38,0),
	LAST_CONTACT_DATE DATE,
	RETENTION_ACTION VARCHAR(30) NOT NULL,
	COMPETITOR_QUOTE_FLAG BOOLEAN NOT NULL DEFAULT FALSE,
	MODEL_VERSION VARCHAR(15) NOT NULL,
	SCORE_DATE DATE NOT NULL,
	CAMPAIGN_ID VARCHAR(20),
	SNAPSHOT_DATE DATE NOT NULL
);
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.BILLING (
	INVOICE_ID VARCHAR(20) NOT NULL,
	POLICY_ID VARCHAR(20) NOT NULL,
	CUSTOMER_ID VARCHAR(20) NOT NULL,
	BILLING_PLAN VARCHAR(15) NOT NULL,
	INSTALLMENT_NUMBER NUMBER(3,0) NOT NULL,
	TOTAL_INSTALLMENTS NUMBER(3,0) NOT NULL,
	INVOICE_DATE DATE NOT NULL,
	DUE_DATE DATE NOT NULL,
	GRACE_PERIOD_END DATE NOT NULL,
	AMOUNT_DUE NUMBER(12,2) NOT NULL,
	AMOUNT_PAID NUMBER(12,2) NOT NULL DEFAULT 0,
	OUTSTANDING_BALANCE NUMBER(12,2) NOT NULL DEFAULT 0,
	LATE_FEE NUMBER(8,2) NOT NULL DEFAULT 0,
	PAYMENT_STATUS VARCHAR(20) NOT NULL,
	PAYMENT_METHOD VARCHAR(15),
	PAYMENT_DATE DATE,
	TRANSACTION_REF VARCHAR(30),
	CANCELLATION_DATE DATE
);
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.CHURN_PRESCRIPTIONS (
	POLICY_ID VARCHAR(20),
	CUSTOMER_ID VARCHAR(20),
	RISK_CATEGORY VARCHAR(25),
	CHURN_PROBABILITY NUMBER(5,4),
	REVENUE_AT_RISK NUMBER(12,2),
	MISSED_PAYMENTS_COUNT NUMBER(38,0),
	NPS_SCORE NUMBER(38,0),
	CLAIM_FREQUENCY NUMBER(38,0),
	CREDIT_SCORE NUMBER(38,0),
	RISK_TIER VARCHAR(10),
	SEGMENT VARCHAR(20),
	STATE VARCHAR(2),
	RETENTION_PRESCRIPTION VARCHAR(16777216),
	GENERATED_AT TIMESTAMP_LTZ(9)
);
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.CLAIMS (
	CLAIM_ID VARCHAR(20) NOT NULL,
	POLICY_ID VARCHAR(20) NOT NULL,
	CUSTOMER_ID VARCHAR(20) NOT NULL,
	CLAIM_DATE DATE NOT NULL,
	LOSS_DATE DATE NOT NULL,
	FNOL_DATE DATE NOT NULL,
	FNOL_CHANNEL VARCHAR(15) NOT NULL,
	REPORTED_BY VARCHAR(15) NOT NULL,
	CLAIM_TYPE VARCHAR(30) NOT NULL,
	CAUSE_OF_LOSS VARCHAR(30),
	CLAIM_AMOUNT NUMBER(12,2) NOT NULL,
	APPROVED_AMOUNT NUMBER(12,2),
	RESERVE_AMOUNT NUMBER(12,2),
	PAID_AMOUNT NUMBER(12,2) DEFAULT 0,
	RECOVERY_AMOUNT NUMBER(12,2) DEFAULT 0,
	STATUS VARCHAR(20) NOT NULL,
	FRAUD_SCORE NUMBER(5,2),
	FRICTION_SCORE NUMBER(5,2),
	ADJUSTER_ID VARCHAR(20),
	RESOLUTION_DAYS NUMBER(38,0),
	INCIDENT_LOCATION VARCHAR(100),
	LITIGATION_FLAG BOOLEAN NOT NULL DEFAULT FALSE,
	CATASTROPHE_CODE VARCHAR(20),
	CLOSED_DATE DATE,
	ESCALATION_FLAG BOOLEAN DEFAULT FALSE,
	FRICTION_REASON VARCHAR(30)
);
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.CLAIMS_COST_FORECAST (
	FORECAST_DATE DATE,
	PREDICTED_COST FLOAT,
	LOWER_BOUND FLOAT,
	UPPER_BOUND FLOAT,
	MODEL_TRAINED_AT TIMESTAMP_LTZ(9)
);
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.CLAIMS_FORECAST (
	POLICY_TYPE VARIANT,
	FORECAST_DATE DATE,
	PREDICTED_CLAIMS FLOAT,
	LOWER_BOUND FLOAT,
	UPPER_BOUND FLOAT,
	FORECAST_TYPE VARCHAR(13),
	MODEL_TRAINED_AT TIMESTAMP_LTZ(9)
);
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.CLAIM_ACTIVITY_LOG (
	ACTIVITY_ID VARCHAR(20) NOT NULL,
	CLAIM_ID VARCHAR(20) NOT NULL,
	ADJUSTER_ID VARCHAR(20) NOT NULL,
	ACTIVITY_DATE TIMESTAMP_NTZ(9) NOT NULL,
	ACTIVITY_TYPE VARCHAR(30) NOT NULL,
	NOTES VARCHAR(200),
	DURATION_MINUTES NUMBER(38,0),
	constraint PK_CLAIM_ACT primary key (ACTIVITY_ID)
)COMMENT='Claim adjuster activity log with timestamped events for workload monitoring and SLA tracking'
;
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.CLAIM_DOCUMENTS (
	DOCUMENT_ID VARCHAR(40) NOT NULL,
	CLAIM_ID VARCHAR(20),
	POLICY_ID VARCHAR(20),
	DOCUMENT_TYPE VARCHAR(40) NOT NULL,
	DATE_OF_LOSS DATE,
	CAUSE_OF_LOSS VARCHAR(200),
	LOSS_DESCRIPTION VARCHAR(2000),
	REPORTED_BY VARCHAR(100),
	CLAIMANT_NAME VARCHAR(100),
	CLAIMANT_CONTACT VARCHAR(200),
	DAMAGE_ESTIMATE NUMBER(14,2),
	LIABILITY_DETERMINATION VARCHAR(100),
	INJURY_TYPE VARCHAR(200),
	RECOVERY_AMOUNT NUMBER(14,2),
	AT_FAULT_PARTY VARCHAR(200),
	ADJUSTER_NAME VARCHAR(100),
	STATUS VARCHAR(30) DEFAULT 'Open',
	EXTRACTED_JSON VARIANT,
	SOURCE_FILE VARCHAR(200),
	INGESTED_BY VARCHAR(50),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (DOCUMENT_ID)
);
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.COVERAGE_DETAILS (
	COVERAGE_ID VARCHAR(30) NOT NULL,
	POLICY_ID VARCHAR(20) NOT NULL,
	COVERAGE_LINE VARCHAR(60) NOT NULL,
	COVERAGE_LIMIT NUMBER(14,2),
	DEDUCTIBLE_AMOUNT NUMBER(12,2),
	DEDUCTIBLE_TYPE VARCHAR(20) DEFAULT 'Flat',
	NOTES VARCHAR(500),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (COVERAGE_ID)
);
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.CUSTOMERS (
	CUSTOMER_ID VARCHAR(20) NOT NULL,
	SALESFORCE_ACCOUNT_ID VARCHAR(20) NOT NULL,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	GENDER VARCHAR(12),
	EMAIL VARCHAR(100) WITH MASKING POLICY INSURANCE_AI_HUB.ANALYTICS.MASK_EMAIL,
	PHONE VARCHAR(20) WITH MASKING POLICY INSURANCE_AI_HUB.ANALYTICS.MASK_PHONE,
	ADDRESS VARCHAR(200),
	CITY VARCHAR(50),
	STATE VARCHAR(2),
	ZIP_CODE VARCHAR(10),
	RISK_TIER VARCHAR(10) NOT NULL,
	CREDIT_SCORE NUMBER(38,0) WITH MASKING POLICY INSURANCE_AI_HUB.ANALYTICS.MASK_CREDIT_SCORE,
	SEGMENT VARCHAR(20) NOT NULL,
	PREFERRED_CONTACT_METHOD VARCHAR(10),
	HOUSEHOLD_ID VARCHAR(20),
	LIFE_EVENT_FLAG VARCHAR(20),
	ANNUAL_INCOME_RANGE VARCHAR(15),
	CUSTOMER_SINCE DATE NOT NULL
);
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.CUSTOMER_ATTRIBUTE_HISTORY (
	HISTORY_ID VARCHAR(20) NOT NULL,
	CUSTOMER_ID VARCHAR(20) NOT NULL,
	ATTRIBUTE_NAME VARCHAR(30) NOT NULL,
	OLD_VALUE VARCHAR(50),
	NEW_VALUE VARCHAR(50) NOT NULL,
	CHANGE_DATE DATE NOT NULL,
	CHANGE_REASON VARCHAR(50) NOT NULL,
	TRIGGERED_BY VARCHAR(20) NOT NULL,
	constraint PK_CUST_HIST primary key (HISTORY_ID)
)COMMENT='Customer attribute change history tracking risk tier, segment, and credit score changes over time'
;
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.CUSTOMER_SURVEYS (
	SURVEY_ID VARCHAR(20) NOT NULL,
	CUSTOMER_ID VARCHAR(20) NOT NULL,
	POLICY_ID VARCHAR(20),
	SURVEY_DATE DATE NOT NULL,
	SURVEY_TYPE VARCHAR(10) NOT NULL,
	NPS_RATING NUMBER(38,0) NOT NULL,
	PROMOTER_CATEGORY VARCHAR(15) NOT NULL,
	SATISFACTION_SCORE NUMBER(3,1),
	COMMENTS VARCHAR(16777216),
	CHANNEL VARCHAR(20) NOT NULL,
	constraint PK_SURVEYS primary key (SURVEY_ID)
)COMMENT='Customer survey responses including NPS ratings, satisfaction scores, and feedback for retention analytics'
;
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.FINANCIAL_LEDGER (
	LEDGER_ID VARCHAR(20) NOT NULL,
	ENTRY_DATE DATE NOT NULL,
	FISCAL_QUARTER VARCHAR(10) NOT NULL,
	ACCOUNT_TYPE VARCHAR(30) NOT NULL,
	ACCOUNT_SUBTYPE VARCHAR(50),
	LINE_OF_BUSINESS VARCHAR(20),
	AMOUNT NUMBER(14,2) NOT NULL,
	DESCRIPTION VARCHAR(200),
	CREATED_AT TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	constraint PK_FINANCIAL_LEDGER primary key (LEDGER_ID)
)COMMENT='Financial ledger entries for loss reserves, investment income, audit adjustments, and operating expenses'
;
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.LOSS_RATIO_ANOMALIES (
	MONTH DATE,
	ACTUAL_LOSS_RATIO FLOAT,
	EXPECTED_LOSS_RATIO FLOAT,
	IS_ANOMALY BOOLEAN,
	ANOMALY_PERCENTILE FLOAT,
	ANOMALY_DISTANCE FLOAT,
	DETECTED_AT TIMESTAMP_LTZ(9)
);
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.PDF_INGESTION_LOG (
	INGESTION_ID VARCHAR(50) NOT NULL DEFAULT UUID_STRING(),
	FILE_NAME VARCHAR(200),
	POLICY_ID VARCHAR(30),
	DOCUMENT_TYPE VARCHAR(50),
	TABLES_UPDATED ARRAY,
	EXTRACTED_JSON VARIANT,
	STATUS VARCHAR(20) DEFAULT 'SUCCESS',
	INGESTED_BY VARCHAR(100),
	INGESTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	NOTES VARCHAR(500)
);
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.POLICIES (
	POLICY_ID VARCHAR(20) NOT NULL,
	POLICY_NUMBER VARCHAR(30) NOT NULL,
	CUSTOMER_ID VARCHAR(20) NOT NULL,
	AGENT_ID VARCHAR(20) NOT NULL,
	POLICY_TYPE VARCHAR(30) NOT NULL,
	LINE_OF_BUSINESS VARCHAR(40) NOT NULL,
	COVERAGE_TIER VARCHAR(15) NOT NULL,
	EFFECTIVE_DATE DATE NOT NULL,
	EXPIRATION_DATE DATE NOT NULL,
	BOUND_DATE DATE NOT NULL,
	POLICY_TERM_MONTHS NUMBER(3,0) NOT NULL,
	ISSUING_STATE VARCHAR(2) NOT NULL,
	PREMIUM_AMOUNT NUMBER(12,2) NOT NULL,
	COVERAGE_AMOUNT NUMBER(14,2) NOT NULL,
	DEDUCTIBLE NUMBER(10,2) NOT NULL,
	STATUS VARCHAR(15) NOT NULL,
	RENEWAL_STATUS VARCHAR(15) NOT NULL,
	ENDORSEMENT_TYPE VARCHAR(30),
	UNDERWRITING_SCORE NUMBER(5,2),
	CREATED_AT TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	EXPENSE_AMOUNT NUMBER(12,2),
	CANCELLATION_DATE DATE,
	CANCELLATION_REASON VARCHAR(200),
	RETURN_PREMIUM NUMBER(12,2),
	BUSINESS_DESCRIPTION VARCHAR(200)
);
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.POLICY_CHANGE_LOG (
	CHANGE_ID VARCHAR(20) NOT NULL,
	POLICY_ID VARCHAR(20) NOT NULL,
	CHANGE_DATE DATE NOT NULL,
	CHANGE_TYPE VARCHAR(30) NOT NULL,
	FIELD_CHANGED VARCHAR(50) NOT NULL,
	OLD_VALUE VARCHAR(100),
	NEW_VALUE VARCHAR(100),
	REASON VARCHAR(100),
	REQUESTED_BY VARCHAR(20),
	CREATED_AT TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	constraint PK_POLICY_CHANGE_LOG primary key (CHANGE_ID)
)COMMENT='Policy mid-term change log tracking tier changes, coverage adjustments, and endorsement modifications'
;
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.POLICY_ENDORSEMENTS (
	ENDORSEMENT_ID VARCHAR(30) NOT NULL,
	POLICY_ID VARCHAR(20) NOT NULL,
	ENDORSEMENT_NAME VARCHAR(100) NOT NULL,
	ENDORSEMENT_LIMIT NUMBER(12,2),
	DESCRIPTION VARCHAR(500),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (ENDORSEMENT_ID)
);
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.POLICY_METADATA (
	METADATA_ID VARCHAR(40) NOT NULL,
	POLICY_ID VARCHAR(20) NOT NULL,
	FIELD_NAME VARCHAR(100) NOT NULL,
	FIELD_VALUE VARCHAR(500),
	FIELD_TYPE VARCHAR(20) DEFAULT 'TEXT',
	SOURCE VARCHAR(30) DEFAULT 'PDF_INTAKE',
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (METADATA_ID)
);
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.PREMIUM_FORECAST (
	FORECAST_DATE DATE,
	PREDICTED_PREMIUM FLOAT,
	LOWER_BOUND FLOAT,
	UPPER_BOUND FLOAT,
	MODEL_TRAINED_AT TIMESTAMP_LTZ(9)
);
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.PRICING_RECOMMENDATIONS (
	STATE VARCHAR(2),
	POLICY_TYPE VARCHAR(30),
	POLICIES NUMBER(18,0),
	AVG_PREMIUM NUMBER(31,0),
	CLAIMS NUMBER(18,0),
	LOSS_RATIO NUMBER(36,1),
	FEMA_DISASTERS NUMBER(18,0),
	SEVERE_WEATHER_ALERTS NUMBER(18,0),
	PRICING_RECOMMENDATION VARCHAR(16777216),
	PRICING_STATUS VARCHAR(11),
	GENERATED_AT TIMESTAMP_LTZ(9)
);
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.PROPERTY_CHARACTERISTICS (
	PROPERTY_ID VARCHAR(20) NOT NULL,
	POLICY_ID VARCHAR(20) NOT NULL,
	CONSTRUCTION_TYPE VARCHAR(30) NOT NULL,
	YEAR_BUILT NUMBER(38,0) NOT NULL,
	SQUARE_FOOTAGE NUMBER(38,0) NOT NULL,
	NUMBER_OF_STORIES NUMBER(38,0) NOT NULL,
	ROOF_TYPE VARCHAR(30) NOT NULL,
	FOUNDATION_TYPE VARCHAR(30) NOT NULL,
	HEATING_TYPE VARCHAR(20),
	ELECTRICAL_UPDATE_YEAR NUMBER(38,0),
	PLUMBING_UPDATE_YEAR NUMBER(38,0),
	ROOF_UPDATE_YEAR NUMBER(38,0),
	FIRE_PROTECTION VARCHAR(20) NOT NULL,
	DISTANCE_FIRE_STATION_MI NUMBER(4,1),
	FLOOD_ZONE VARCHAR(15),
	PROPERTY_USE VARCHAR(30) NOT NULL,
	REPLACEMENT_COST NUMBER(14,2) NOT NULL,
	PROTECTION_CLASS VARCHAR(20),
	constraint PK_PROPERTY primary key (PROPERTY_ID)
)COMMENT='Property construction characteristics for Home/Commercial policies — masonry type, roof, year built, flood zone for underwriting'
;
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.REINSURANCE_RECOVERIES (
	RECOVERY_ID VARCHAR(20) NOT NULL,
	TREATY_ID VARCHAR(20) NOT NULL,
	CLAIM_ID VARCHAR(20) NOT NULL,
	GROSS_LOSS NUMBER(14,2) NOT NULL,
	CEDED_AMOUNT NUMBER(14,2) NOT NULL,
	RECOVERED_AMOUNT NUMBER(14,2) NOT NULL,
	RECOVERY_DATE DATE,
	STATUS VARCHAR(15) NOT NULL,
	constraint PK_REINSURANCE_RECOVERIES primary key (RECOVERY_ID),
	constraint FK_RR_TREATY foreign key (TREATY_ID) references INSURANCE_AI_HUB.ANALYTICS.REINSURANCE_TREATIES(TREATY_ID)
);
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.REINSURANCE_TREATIES (
	TREATY_ID VARCHAR(20) NOT NULL,
	TREATY_NAME VARCHAR(100) NOT NULL,
	TREATY_TYPE VARCHAR(30) NOT NULL,
	REINSURER_NAME VARCHAR(100) NOT NULL,
	RETENTION_LIMIT NUMBER(14,2) NOT NULL,
	CESSION_RATE NUMBER(5,4),
	MAX_CESSION NUMBER(14,2),
	EFFECTIVE_DATE DATE NOT NULL,
	EXPIRATION_DATE DATE NOT NULL,
	LINE_OF_BUSINESS VARCHAR(20),
	STATUS VARCHAR(15) NOT NULL,
	constraint PK_REINSURANCE_TREATIES primary key (TREATY_ID)
)COMMENT='Reinsurance treaty definitions with retention limits, cession rates, and reinsurer details'
;
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.VEHICLE_DETAILS (
	VEHICLE_ID VARCHAR(20) NOT NULL,
	POLICY_ID VARCHAR(20) NOT NULL,
	VIN VARCHAR(17) NOT NULL,
	MAKE VARCHAR(30) NOT NULL,
	MODEL VARCHAR(50) NOT NULL,
	YEAR NUMBER(38,0) NOT NULL,
	BODY_TYPE VARCHAR(20) NOT NULL,
	ENGINE_TYPE VARCHAR(15) NOT NULL,
	SAFETY_RATING NUMBER(38,0),
	ANNUAL_MILEAGE NUMBER(38,0),
	GARAGE_ZIP VARCHAR(10),
	constraint PK_VEHICLE primary key (VEHICLE_ID)
)COMMENT='Vehicle details for auto policies — make, model, year, safety rating for claims analysis and risk scoring'
;
create or replace TABLE INSURANCE_AI_HUB.ANALYTICS.VEHICLE_SCHEDULE (
	VEHICLE_ID VARCHAR(30) NOT NULL,
	POLICY_ID VARCHAR(20) NOT NULL,
	UNIT_NUMBER NUMBER(3,0),
	YEAR_MAKE_MODEL VARCHAR(100),
	VIN VARCHAR(20),
	GARAGING_LOCATION VARCHAR(100),
	STATED_VALUE NUMBER(12,2),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (VEHICLE_ID)
);
create or replace view INSURANCE_AI_HUB.ANALYTICS.V_CLAIMS_COST_TS(
	DS,
	TOTAL_INCURRED
) as
SELECT
    DATE_TRUNC('month', CLAIM_DATE)::TIMESTAMP_NTZ AS DS,
    ROUND(SUM(CLAIM_AMOUNT), 2)::FLOAT AS TOTAL_INCURRED
FROM INSURANCE_AI_HUB.ANALYTICS.CLAIMS
GROUP BY DATE_TRUNC('month', CLAIM_DATE) ORDER BY DS;
create or replace view INSURANCE_AI_HUB.ANALYTICS.V_CLAIMS_MONTHLY_TS(
	SERIES,
	DS,
	CLAIM_COUNT,
	TOTAL_INCURRED,
	AVG_FRAUD_SCORE
) as
SELECT
    p.POLICY_TYPE AS SERIES,
    DATE_TRUNC('month', cl.CLAIM_DATE)::TIMESTAMP_NTZ AS DS,
    COUNT(*)::FLOAT AS CLAIM_COUNT,
    ROUND(SUM(cl.CLAIM_AMOUNT), 2)::FLOAT AS TOTAL_INCURRED,
    ROUND(AVG(cl.FRAUD_SCORE), 2)::FLOAT AS AVG_FRAUD_SCORE
FROM INSURANCE_AI_HUB.ANALYTICS.CLAIMS cl
JOIN INSURANCE_AI_HUB.ANALYTICS.POLICIES p ON p.POLICY_ID = cl.POLICY_ID
GROUP BY p.POLICY_TYPE, DATE_TRUNC('month', cl.CLAIM_DATE)
ORDER BY SERIES, DS;
create or replace view INSURANCE_AI_HUB.ANALYTICS.V_CLAIMS_VOLUME_TS(
	SERIES,
	DS,
	CLAIM_COUNT
) as
SELECT
    p.POLICY_TYPE AS SERIES,
    DATE_TRUNC('month', cl.CLAIM_DATE)::TIMESTAMP_NTZ AS DS,
    COUNT(*)::FLOAT AS CLAIM_COUNT
FROM INSURANCE_AI_HUB.ANALYTICS.CLAIMS cl
JOIN INSURANCE_AI_HUB.ANALYTICS.POLICIES p ON p.POLICY_ID = cl.POLICY_ID
GROUP BY p.POLICY_TYPE, DATE_TRUNC('month', cl.CLAIM_DATE)
ORDER BY SERIES, DS;
create or replace view INSURANCE_AI_HUB.ANALYTICS.V_LOSS_RATIO_TEST(
	DS,
	LOSS_RATIO
) as
SELECT DS, LOSS_RATIO FROM INSURANCE_AI_HUB.ANALYTICS.V_LOSS_RATIO_TS
WHERE DS >= DATEADD('month', -3, (SELECT MAX(DS) FROM INSURANCE_AI_HUB.ANALYTICS.V_LOSS_RATIO_TS));
create or replace view INSURANCE_AI_HUB.ANALYTICS.V_LOSS_RATIO_TRAIN(
	DS,
	LOSS_RATIO
) as
SELECT DS, LOSS_RATIO FROM INSURANCE_AI_HUB.ANALYTICS.V_LOSS_RATIO_TS
WHERE DS < DATEADD('month', -3, (SELECT MAX(DS) FROM INSURANCE_AI_HUB.ANALYTICS.V_LOSS_RATIO_TS));
create or replace view INSURANCE_AI_HUB.ANALYTICS.V_LOSS_RATIO_TS(
	DS,
	LOSS_RATIO
) as
SELECT
    DATE_TRUNC('month', cl.CLAIM_DATE)::TIMESTAMP_NTZ AS DS,
    ROUND(SUM(cl.CLAIM_AMOUNT) / NULLIF(SUM(p.PREMIUM_AMOUNT), 0) * 100, 2)::FLOAT AS LOSS_RATIO
FROM INSURANCE_AI_HUB.ANALYTICS.CLAIMS cl
JOIN INSURANCE_AI_HUB.ANALYTICS.POLICIES p ON p.POLICY_ID = cl.POLICY_ID
GROUP BY DATE_TRUNC('month', cl.CLAIM_DATE) ORDER BY DS;
create or replace view INSURANCE_AI_HUB.ANALYTICS.V_PREMIUM_TS(
	DS,
	TOTAL_PREMIUM
) as
SELECT
    DATE_TRUNC('month', EFFECTIVE_DATE)::TIMESTAMP_NTZ AS DS,
    ROUND(SUM(PREMIUM_AMOUNT), 2)::FLOAT AS TOTAL_PREMIUM
FROM INSURANCE_AI_HUB.ANALYTICS.POLICIES
GROUP BY DATE_TRUNC('month', EFFECTIVE_DATE) ORDER BY DS;
CREATE OR REPLACE PROCEDURE INSURANCE_AI_HUB.ANALYTICS.AUTO_INGEST_PDFS()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
    LET files_processed INT := 0;
    LET cursor_result RESULTSET;

    cursor_result := (
        SELECT RELATIVE_PATH
        FROM INSURANCE_AI_HUB.ANALYTICS.PDF_INTAKE_STREAM
        WHERE METADATA$ACTION = ''INSERT''
          AND RELATIVE_PATH ILIKE ''%.pdf''
    );

    LET c CURSOR FOR cursor_result;
    FOR row_var IN c DO
        LET file_path VARCHAR := row_var.RELATIVE_PATH;

        BEGIN
            LET parsed VARCHAR;
            SELECT SNOWFLAKE.CORTEX.PARSE_DOCUMENT(
                ''@INSURANCE_AI_HUB.ANALYTICS.PDF_INTAKE_STAGE'',
                :file_path,
                {''mode'': ''LAYOUT''}
            ):content::VARCHAR INTO :parsed;

            IF (:parsed IS NULL OR LENGTH(:parsed) < 10) THEN
                INSERT INTO INSURANCE_AI_HUB.ANALYTICS.PDF_INGESTION_LOG
                (FILE_NAME, STATUS, INGESTED_BY, DOCUMENT_TYPE)
                VALUES (:file_path, ''PARSE_FAILED'', ''AUTO_INGEST'', ''Unknown'');
                CONTINUE;
            END IF;

            LET extract_prompt VARCHAR := ''Extract from this insurance document. Return ONLY valid JSON with keys: policy_number, policy_type, named_insured, first_name, last_name, address, city, state, zip_code, effective_date, expiration_date, annual_premium, coverage_amount, deductible. Use null for missing. Dates YYYY-MM-DD. Numbers only.\\n\\nDOCUMENT:\\n'' || LEFT(:parsed, 6000);

            LET llm_response VARCHAR;
            SELECT SNOWFLAKE.CORTEX.COMPLETE(''claude-sonnet-4-6'', :extract_prompt) INTO :llm_response;

            LET clean_json VARCHAR := TRIM(:llm_response);
            IF (LEFT(:clean_json, 3) = ''```'') THEN
                LET nl_pos INT := POSITION(CHR(10) IN :clean_json);
                clean_json := SUBSTR(:clean_json, :nl_pos + 1);
                LET last_fence INT := LENGTH(:clean_json) - 3;
                clean_json := TRIM(LEFT(:clean_json, :last_fence));
            END IF;

            LET extracted VARIANT := TRY_PARSE_JSON(:clean_json);
            IF (:extracted IS NULL) THEN
                INSERT INTO INSURANCE_AI_HUB.ANALYTICS.PDF_INGESTION_LOG
                (FILE_NAME, STATUS, INGESTED_BY, DOCUMENT_TYPE)
                VALUES (:file_path, ''JSON_PARSE_FAILED'', ''AUTO_INGEST'', ''Unknown'');
                CONTINUE;
            END IF;

            LET policy_id VARCHAR := REPLACE(COALESCE(:extracted:policy_number::VARCHAR, ''''), ''""'', '''');
            IF (:policy_id IS NULL OR :policy_id = '''' OR :policy_id = ''null'') THEN
                INSERT INTO INSURANCE_AI_HUB.ANALYTICS.PDF_INGESTION_LOG
                (FILE_NAME, STATUS, INGESTED_BY, DOCUMENT_TYPE)
                VALUES (:file_path, ''NO_POLICY_NUMBER'', ''AUTO_INGEST'', ''Unknown'');
                CONTINUE;
            END IF;

            LET cust_id VARCHAR := ''CUST-AUTO-'' || RIGHT(:policy_id, 5);
            LET ptype VARCHAR := REPLACE(COALESCE(:extracted:policy_type::VARCHAR, ''Unknown''), ''""'', '''');
            LET first_nm VARCHAR := REPLACE(COALESCE(:extracted:first_name::VARCHAR, :extracted:named_insured::VARCHAR, ''Unknown''), ''""'', '''');
            LET last_nm VARCHAR := REPLACE(COALESCE(:extracted:last_name::VARCHAR, ''''), ''""'', '''');
            LET addr VARCHAR := REPLACE(COALESCE(:extracted:address::VARCHAR, ''''), ''""'', '''');
            LET city_val VARCHAR := REPLACE(COALESCE(:extracted:city::VARCHAR, ''''), ''""'', '''');
            LET st_code VARCHAR := REPLACE(COALESCE(:extracted:state::VARCHAR, ''''), ''""'', '''');
            LET zip_val VARCHAR := REPLACE(COALESCE(:extracted:zip_code::VARCHAR, ''''), ''""'', '''');
            LET eff_dt VARCHAR := REPLACE(COALESCE(:extracted:effective_date::VARCHAR, ''''), ''""'', '''');
            LET exp_dt VARCHAR := REPLACE(COALESCE(:extracted:expiration_date::VARCHAR, ''''), ''""'', '''');
            LET prem NUMBER(12,2) := COALESCE(TRY_TO_NUMBER(:extracted:annual_premium::VARCHAR, 12, 2), 0);
            LET cov NUMBER(14,2) := COALESCE(TRY_TO_NUMBER(:extracted:coverage_amount::VARCHAR, 14, 2), 0);
            LET ded NUMBER(10,2) := COALESCE(TRY_TO_NUMBER(:extracted:deductible::VARCHAR, 10, 2), 0);
            LET lob VARCHAR := CASE WHEN LOWER(:ptype) LIKE ''%commercial%'' THEN ''Commercial Lines'' ELSE ''Personal Lines'' END;

            MERGE INTO INSURANCE_AI_HUB.ANALYTICS.CUSTOMERS t
            USING (SELECT :cust_id AS CID) s ON t.CUSTOMER_ID = s.CID
            WHEN NOT MATCHED THEN INSERT (CUSTOMER_ID, SALESFORCE_ACCOUNT_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, RISK_TIER, SEGMENT, CREDIT_SCORE, CUSTOMER_SINCE, ADDRESS, CITY, STATE, ZIP_CODE)
            VALUES (:cust_id, ''SF-AUTO-'' || RIGHT(:policy_id, 5), :first_nm, :last_nm, ''1990-01-01''::DATE, ''Medium'', ''Standard'', 700, CURRENT_DATE(), :addr, :city_val, :st_code, :zip_val);

            MERGE INTO INSURANCE_AI_HUB.ANALYTICS.POLICIES t
            USING (SELECT :policy_id AS PID) s ON t.POLICY_ID = s.PID
            WHEN NOT MATCHED THEN INSERT (POLICY_ID, POLICY_NUMBER, CUSTOMER_ID, AGENT_ID, POLICY_TYPE, LINE_OF_BUSINESS, COVERAGE_TIER, EFFECTIVE_DATE, EXPIRATION_DATE, BOUND_DATE, POLICY_TERM_MONTHS, ISSUING_STATE, PREMIUM_AMOUNT, COVERAGE_AMOUNT, DEDUCTIBLE, STATUS, RENEWAL_STATUS)
            VALUES (:policy_id, :policy_id, :cust_id, ''AGT-AUTO-001'', :ptype, :lob, ''Standard'', TRY_TO_DATE(:eff_dt), TRY_TO_DATE(:exp_dt), TRY_TO_DATE(:eff_dt), 12, :st_code, :prem, :cov, :ded, ''Active'', ''Auto-Renew'');

            INSERT INTO INSURANCE_AI_HUB.ANALYTICS.PDF_INGESTION_LOG
            (FILE_NAME, POLICY_ID, DOCUMENT_TYPE, TABLES_UPDATED, EXTRACTED_JSON, STATUS, INGESTED_BY)
            SELECT :file_path, :policy_id, :ptype, ARRAY_CONSTRUCT(''CUSTOMERS'', ''POLICIES''), :extracted, ''SUCCESS'', ''AUTO_INGEST'';

            files_processed := :files_processed + 1;

        EXCEPTION
            WHEN OTHER THEN
                INSERT INTO INSURANCE_AI_HUB.ANALYTICS.PDF_INGESTION_LOG
                (FILE_NAME, STATUS, INGESTED_BY, NOTES)
                VALUES (:file_path, ''ERROR'', ''AUTO_INGEST'', SQLERRM);
        END;
    END FOR;

    RETURN ''Processed '' || :files_processed::VARCHAR || '' PDF(s)'';
END;
';
create or replace stream INSURANCE_AI_HUB.ANALYTICS.PDF_INTAKE_STREAM on directory(@PDF_INTAKE_STAGE);
create or replace task INSURANCE_AI_HUB.ANALYTICS.AUTO_INGEST_PDF_TASK
	warehouse=COMPUTE_WH
	schedule='5 MINUTE'
	when SYSTEM$STREAM_HAS_DATA('INSURANCE_AI_HUB.ANALYTICS.PDF_INTAKE_STREAM')
	as CALL INSURANCE_AI_HUB.ANALYTICS.AUTO_INGEST_PDFS();
create or replace task INSURANCE_AI_HUB.ANALYTICS.DAILY_ENRICHMENT_ROOT
	warehouse=COMPUTE_WH
	schedule='USING CRON 0 2 * * * UTC'
	COMMENT='Root task: triggers daily refresh of enrichment tables at 2 AM UTC'
	as SELECT 1;
create or replace task INSURANCE_AI_HUB.ANALYTICS.DAILY_REFRESH_CLAIM_ACTIVITY_LOG
	warehouse=COMPUTE_WH
	after INSURANCE_AI_HUB.ANALYTICS.DAILY_ENRICHMENT_ROOT
	as INSERT INTO INSURANCE_AI_HUB.ANALYTICS.CLAIM_ACTIVITY_LOG (ACTIVITY_ID, CLAIM_ID, ADJUSTER_ID, ACTIVITY_DATE, ACTIVITY_TYPE, NOTES, DURATION_MINUTES)
    WITH next_id AS (
        SELECT COALESCE(MAX(REPLACE(ACTIVITY_ID, 'ACT-', '')::INT), 0) AS max_id
        FROM INSURANCE_AI_HUB.ANALYTICS.CLAIM_ACTIVITY_LOG
    ),
    open_claims AS (
        SELECT CLAIM_ID, ADJUSTER_ID,
               ROW_NUMBER() OVER (ORDER BY RANDOM()) AS rn
        FROM INSURANCE_AI_HUB.ANALYTICS.CLAIMS
        WHERE CLAIM_STATUS IN ('Open', 'Under Review', 'Pending')
          AND ADJUSTER_ID IS NOT NULL
        LIMIT 200
    ),
    activity_types_arr AS (
        SELECT ARRAY_CONSTRUCT(
            'InitialReview','ContactClaimant','RequestDocuments','FieldInspection',
            'DamageAssessment','CoverageVerification','ApprovalSubmission',
            'FollowUpCall','ThirdPartyContact','SupervisorReview'
        ) AS arr
    )
    SELECT
        'ACT-' || LPAD((ni.max_id + oc.rn)::VARCHAR, 6, '0'),
        oc.CLAIM_ID,
        oc.ADJUSTER_ID,
        DATEADD('second', UNIFORM(0, 86400, RANDOM()), CURRENT_DATE()::TIMESTAMP_NTZ),
        at.arr[MOD(ABS(HASH(oc.CLAIM_ID || oc.rn::VARCHAR)), 10)]::VARCHAR,
        'Daily activity recorded by system.',
        UNIFORM(5, 120, RANDOM())
    FROM open_claims oc
    CROSS JOIN next_id ni
    CROSS JOIN activity_types_arr at;
create or replace task INSURANCE_AI_HUB.ANALYTICS.DAILY_REFRESH_CUSTOMER_ATTR_HISTORY
	warehouse=COMPUTE_WH
	after INSURANCE_AI_HUB.ANALYTICS.DAILY_ENRICHMENT_ROOT
	as INSERT INTO INSURANCE_AI_HUB.ANALYTICS.CUSTOMER_ATTRIBUTE_HISTORY (HISTORY_ID, CUSTOMER_ID, ATTRIBUTE_NAME, OLD_VALUE, NEW_VALUE, CHANGE_DATE, CHANGE_REASON, TRIGGERED_BY)
    WITH next_id AS (
        SELECT COALESCE(MAX(REPLACE(HISTORY_ID, 'CHIST-', '')::INT), 0) AS max_id
        FROM INSURANCE_AI_HUB.ANALYTICS.CUSTOMER_ATTRIBUTE_HISTORY
    ),
    changed_customers AS (
        SELECT CUSTOMER_ID, RISK_TIER, SEGMENT, CREDIT_SCORE,
               ROW_NUMBER() OVER (ORDER BY RANDOM()) AS rn
        FROM INSURANCE_AI_HUB.ANALYTICS.CUSTOMERS
        WHERE MOD(ABS(HASH(CUSTOMER_ID || CURRENT_DATE()::VARCHAR)), 100) < 2
        LIMIT 50
    )
    SELECT
        'CHIST-' || LPAD((ni.max_id + cc.rn)::VARCHAR, 6, '0'),
        cc.CUSTOMER_ID,
        CASE MOD(cc.rn, 3)
            WHEN 0 THEN 'RISK_TIER' WHEN 1 THEN 'SEGMENT' ELSE 'CREDIT_SCORE'
        END,
        CASE MOD(cc.rn, 3)
            WHEN 0 THEN cc.RISK_TIER
            WHEN 1 THEN cc.SEGMENT
            ELSE cc.CREDIT_SCORE::VARCHAR
        END,
        CASE MOD(cc.rn, 3)
            WHEN 0 THEN CASE MOD(ABS(HASH(cc.CUSTOMER_ID || 'new')), 4)
                            WHEN 0 THEN 'Low' WHEN 1 THEN 'Medium' WHEN 2 THEN 'High' ELSE 'Critical' END
            WHEN 1 THEN CASE MOD(ABS(HASH(cc.CUSTOMER_ID || 'seg')), 3)
                            WHEN 0 THEN 'Budget' WHEN 1 THEN 'Standard' ELSE 'Premium' END
            ELSE UNIFORM(300, 850, RANDOM())::VARCHAR
        END,
        CURRENT_DATE(),
        CASE MOD(ABS(HASH(cc.CUSTOMER_ID || CURRENT_DATE()::VARCHAR)), 5)
            WHEN 0 THEN 'Annual Review' WHEN 1 THEN 'Claim Filed' WHEN 2 THEN 'Credit Update'
            WHEN 3 THEN 'Policy Renewal' ELSE 'Risk Reassessment'
        END,
        CASE MOD(ABS(HASH(cc.CUSTOMER_ID)), 4)
            WHEN 0 THEN 'Renewal' WHEN 1 THEN 'Claim' WHEN 2 THEN 'SystemUpdate' ELSE 'AnnualReview'
        END
    FROM changed_customers cc
    CROSS JOIN next_id ni;
create or replace task INSURANCE_AI_HUB.ANALYTICS.DAILY_REFRESH_ML_MODELS
	warehouse=COMPUTE_WH
	after INSURANCE_AI_HUB.ANALYTICS.DAILY_ENRICHMENT_ROOT
	as CREATE OR REPLACE SNOWFLAKE.ML.FORECAST INSURANCE_AI_HUB.ANALYTICS.CLAIMS_VOLUME_MODEL(
        INPUT_DATA => TABLE(INSURANCE_AI_HUB.ANALYTICS.V_CLAIMS_VOLUME_TS),
        SERIES_COLNAME => 'SERIES',
        TIMESTAMP_COLNAME => 'DS',
        TARGET_COLNAME => 'CLAIM_COUNT'
    );
create or replace task INSURANCE_AI_HUB.ANALYTICS.DAILY_REFRESH_VEHICLE_DETAILS
	warehouse=COMPUTE_WH
	after INSURANCE_AI_HUB.ANALYTICS.DAILY_ENRICHMENT_ROOT
	as INSERT INTO INSURANCE_AI_HUB.ANALYTICS.VEHICLE_DETAILS (VEHICLE_ID, POLICY_ID, VIN, MAKE, MODEL, YEAR, BODY_TYPE, ENGINE_TYPE, SAFETY_RATING, ANNUAL_MILEAGE, GARAGE_ZIP)
    WITH new_policies AS (
        SELECT p.POLICY_ID, p.CUSTOMER_ID, c.ZIP_CODE,
               ROW_NUMBER() OVER (ORDER BY p.POLICY_ID) AS rn
        FROM INSURANCE_AI_HUB.ANALYTICS.POLICIES p
        JOIN INSURANCE_AI_HUB.ANALYTICS.CUSTOMERS c ON c.CUSTOMER_ID = p.CUSTOMER_ID
        WHERE p.POLICY_TYPE IN ('PersonalAuto','CommercialAuto')
          AND p.POLICY_ID NOT IN (SELECT POLICY_ID FROM INSURANCE_AI_HUB.ANALYTICS.VEHICLE_DETAILS)
    ),
    makes AS (
        SELECT column1 AS VMAKE, column2 AS VMODEL, column3 AS VBODY,
               ROW_NUMBER() OVER (ORDER BY column1, column2) AS mrn,
               COUNT(*) OVER () AS mtotal
        FROM VALUES
            ('Toyota','Camry','Sedan'),('Toyota','RAV4','SUV'),('Honda','Civic','Sedan'),
            ('Honda','CR-V','SUV'),('Ford','F-150','Truck'),('Ford','Explorer','SUV'),
            ('Chevrolet','Silverado','Truck'),('Chevrolet','Equinox','SUV'),
            ('Tesla','Model 3','Sedan'),('Tesla','Model Y','SUV'),
            ('BMW','3 Series','Sedan'),('BMW','X5','SUV'),
            ('Hyundai','Tucson','SUV'),('Kia','Sportage','SUV'),
            ('Nissan','Rogue','SUV'),('Subaru','Outback','Wagon')
    )
    SELECT
        'VEH-' || LPAD(
            ((SELECT COALESCE(MAX(REPLACE(VEHICLE_ID, 'VEH-', '')::INT), 0) FROM INSURANCE_AI_HUB.ANALYTICS.VEHICLE_DETAILS)
            + np.rn)::VARCHAR, 5, '0'),
        np.POLICY_ID,
        UPPER(SUBSTR(MD5(np.POLICY_ID), 1, 17)),
        m.VMAKE, m.VMODEL,
        UNIFORM(2015, 2025, RANDOM()),
        m.VBODY,
        CASE MOD(ABS(HASH(np.POLICY_ID)), 5)
            WHEN 0 THEN 'Hybrid' WHEN 1 THEN 'Electric' WHEN 2 THEN 'Diesel' ELSE 'Gasoline'
        END,
        UNIFORM(1, 5, RANDOM()),
        UNIFORM(5000, 25000, RANDOM()),
        np.ZIP_CODE
    FROM new_policies np
    JOIN makes m ON m.mrn = MOD(np.rn - 1, m.mtotal) + 1;
create or replace task INSURANCE_AI_HUB.ANALYTICS.DAILY_UPDATE_FRICTION_REASON
	warehouse=COMPUTE_WH
	after INSURANCE_AI_HUB.ANALYTICS.DAILY_ENRICHMENT_ROOT
	as UPDATE INSURANCE_AI_HUB.ANALYTICS.CLAIMS
    SET FRICTION_REASON = CASE MOD(ABS(HASH(CLAIM_ID || 'fr')), 6)
        WHEN 0 THEN 'Documentation Delay'
        WHEN 1 THEN 'Adjuster Reassignment'
        WHEN 2 THEN 'Dispute Resolution'
        WHEN 3 THEN 'Third Party Response'
        WHEN 4 THEN 'System Error'
        ELSE 'Policy Verification'
    END
    WHERE FRICTION_SCORE > 3.0 AND FRICTION_REASON IS NULL;
create or replace masking policy INSURANCE_AI_HUB.ANALYTICS.MASK_CREDIT_SCORE as (VAL NUMBER(38,0)) 
returns NUMBER(38,0) ->
CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'EXECUTIVE', 'UNDERWRITER') THEN val
    ELSE NULL
  END
;
create or replace masking policy INSURANCE_AI_HUB.ANALYTICS.MASK_EMAIL as (VAL VARCHAR) 
returns VARCHAR ->
CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'EXECUTIVE') THEN val
    ELSE REGEXP_REPLACE(val, '(^[^@]{2})[^@]*(@.*)', '\\1****\\2')
  END
;
create or replace masking policy INSURANCE_AI_HUB.ANALYTICS.MASK_PHONE as (VAL VARCHAR) 
returns VARCHAR ->
CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'EXECUTIVE') THEN val
    ELSE '(***) ***-' || RIGHT(val, 4)
  END
;
create or replace schema INSURANCE_AI_HUB.DATA_QUALITY COMMENT='Data quality observability: rules, execution results, table scores, and column-level health metrics';

create or replace TABLE INSURANCE_AI_HUB.DATA_QUALITY.DQ_COLUMN_HEALTH (
	HEALTH_ID VARCHAR(20) NOT NULL,
	SCHEMA_NAME VARCHAR(30) NOT NULL,
	TABLE_NAME VARCHAR(30) NOT NULL,
	COLUMN_NAME VARCHAR(50) NOT NULL,
	CHECK_DATE DATE NOT NULL,
	NULL_RATE NUMBER(5,2) NOT NULL,
	DUPLICATE_RATE NUMBER(5,2) NOT NULL,
	OUTLIER_RATE NUMBER(5,2) NOT NULL,
	DISTINCT_COUNT NUMBER(38,0) NOT NULL,
	HEALTH_SCORE NUMBER(5,2) NOT NULL,
	DATA_TYPE_CONSISTENCY NUMBER(5,2) NOT NULL,
	FRESHNESS_HOURS NUMBER(6,1) NOT NULL,
	STATUS VARCHAR(10) NOT NULL
);
create or replace TABLE INSURANCE_AI_HUB.DATA_QUALITY.DQ_RESULTS (
	RESULT_ID VARCHAR(20) NOT NULL,
	RULE_ID VARCHAR(20) NOT NULL,
	TARGET_TABLE VARCHAR(30) NOT NULL,
	RUN_DATE TIMESTAMP_NTZ(9) NOT NULL,
	TOTAL_RECORDS NUMBER(38,0) NOT NULL,
	PASSED_RECORDS NUMBER(38,0) NOT NULL,
	FAILED_RECORDS NUMBER(38,0) NOT NULL,
	PASS_RATE NUMBER(5,2) NOT NULL,
	STATUS VARCHAR(10) NOT NULL,
	EXECUTION_TIME_MS NUMBER(38,0) NOT NULL,
	RUN_BY VARCHAR(50) NOT NULL,
	PIPELINE_RUN_ID VARCHAR(30) NOT NULL,
	ANOMALY_SCORE NUMBER(4,3),
	ERROR_SAMPLE VARCHAR(16777216)
);
create or replace TABLE INSURANCE_AI_HUB.DATA_QUALITY.DQ_RULES (
	RULE_ID VARCHAR(20) NOT NULL,
	RULE_NAME VARCHAR(100) NOT NULL,
	RULE_DESCRIPTION VARCHAR(16777216) NOT NULL,
	TARGET_SCHEMA VARCHAR(30) NOT NULL,
	TARGET_TABLE VARCHAR(30) NOT NULL,
	TARGET_COLUMN VARCHAR(50),
	RULE_TYPE VARCHAR(20) NOT NULL,
	SEVERITY VARCHAR(10) NOT NULL,
	THRESHOLD NUMBER(5,2) NOT NULL,
	IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
	SOURCE_SYSTEM VARCHAR(30) NOT NULL,
	PIPELINE_NAME VARCHAR(50) NOT NULL,
	OWNER VARCHAR(50) NOT NULL
);
create or replace TABLE INSURANCE_AI_HUB.DATA_QUALITY.DQ_SCORES (
	SCORE_ID VARCHAR(20) NOT NULL,
	SCHEMA_NAME VARCHAR(30) NOT NULL,
	TABLE_NAME VARCHAR(30) NOT NULL,
	SOURCE_SYSTEM VARCHAR(30) NOT NULL,
	SCORE_DATE DATE NOT NULL,
	COMPLETENESS_SCORE NUMBER(5,2) NOT NULL,
	UNIQUENESS_SCORE NUMBER(5,2) NOT NULL,
	VALIDITY_SCORE NUMBER(5,2) NOT NULL,
	TIMELINESS_SCORE NUMBER(5,2) NOT NULL,
	CONSISTENCY_SCORE NUMBER(5,2) NOT NULL,
	OVERALL_SCORE NUMBER(5,2) NOT NULL,
	TREND VARCHAR(10) NOT NULL,
	RECORDS_ASSESSED NUMBER(38,0) NOT NULL,
	RULES_EVALUATED NUMBER(38,0) NOT NULL
);
create or replace TABLE INSURANCE_AI_HUB.DATA_QUALITY.SCHEMA_AUDIT_LOG (
	AUDIT_ID VARCHAR(20) NOT NULL,
	SCHEMA_NAME VARCHAR(30) NOT NULL,
	TABLE_NAME VARCHAR(30) NOT NULL,
	COLUMN_NAME VARCHAR(50),
	EVENT_TYPE VARCHAR(30) NOT NULL,
	OLD_VALUE VARCHAR(200),
	NEW_VALUE VARCHAR(200),
	DETECTED_AT TIMESTAMP_NTZ(9) NOT NULL,
	SEVERITY VARCHAR(10) NOT NULL,
	ACKNOWLEDGED BOOLEAN NOT NULL DEFAULT FALSE,
	ACKNOWLEDGED_BY VARCHAR(50),
	constraint PK_SCHEMA_AUDIT primary key (AUDIT_ID)
)COMMENT='Schema drift detection log tracking column additions, removals, type changes, and renames across all schemas'
;
create or replace schema INSURANCE_AI_HUB.DOCUMENTS COMMENT='Policy document intelligence: full contract text and chunked embeddings for RAG/Cortex Search';

create or replace TABLE INSURANCE_AI_HUB.DOCUMENTS.DOCUMENT_CHUNKS (
	CHUNK_ID VARCHAR(20) NOT NULL,
	DOCUMENT_ID VARCHAR(20) NOT NULL,
	CHUNK_INDEX NUMBER(38,0) NOT NULL,
	CHUNK_TEXT VARCHAR(16777216) NOT NULL,
	TOKEN_COUNT NUMBER(38,0) NOT NULL,
	EMBEDDING_MODEL VARCHAR(30) NOT NULL DEFAULT 'arctic-embed-m',
	constraint PK_CHUNKS primary key (CHUNK_ID),
	constraint FK_CHUNKS_DOC foreign key (DOCUMENT_ID) references INSURANCE_AI_HUB.DOCUMENTS.POLICY_DOCUMENTS(DOCUMENT_ID)
)COMMENT='Chunked policy document text (500-1000 tokens) for vector embedding and RAG/Cortex Search retrieval'
;
create or replace TABLE INSURANCE_AI_HUB.DOCUMENTS.POLICY_DOCUMENTS (
	DOCUMENT_ID VARCHAR(20) NOT NULL,
	POLICY_ID VARCHAR(20) NOT NULL,
	DOCUMENT_TYPE VARCHAR(30) NOT NULL,
	TITLE VARCHAR(200) NOT NULL,
	CONTENT VARCHAR(16777216) NOT NULL,
	SUMMARY VARCHAR(16777216),
	EFFECTIVE_DATE DATE NOT NULL,
	EXPIRATION_DATE DATE,
	VERSION NUMBER(38,0) NOT NULL DEFAULT 1,
	LANGUAGE VARCHAR(10) NOT NULL DEFAULT 'EN',
	FILE_FORMAT VARCHAR(10) NOT NULL DEFAULT 'PDF',
	CREATED_AT TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	SOURCE_SYSTEM VARCHAR(20),
	FILING_STATE VARCHAR(2),
	REGULATORY_APPROVAL_DATE DATE,
	FORM_NUMBER VARCHAR(20),
	constraint PK_POLICY_DOCS primary key (DOCUMENT_ID)
)COMMENT='Full policy document text including contracts, endorsements, exclusions, declarations, and riders'
;
create or replace TABLE INSURANCE_AI_HUB.DOCUMENTS.RAG_QUERY_LOG (
	QUERY_ID VARCHAR(20) NOT NULL,
	USER_ROLE VARCHAR(30) NOT NULL,
	QUERY_TEXT VARCHAR(16777216) NOT NULL,
	QUERY_DATE TIMESTAMP_NTZ(9) NOT NULL,
	DOCUMENTS_RETURNED NUMBER(38,0) NOT NULL,
	CHUNKS_RETRIEVED NUMBER(38,0) NOT NULL,
	RESPONSE_TIME_MS NUMBER(38,0) NOT NULL,
	QUERY_SOURCE VARCHAR(30) NOT NULL,
	RELEVANCE_SCORE NUMBER(5,4),
	POLICY_ID VARCHAR(20),
	constraint PK_RAG_QUERY primary key (QUERY_ID)
)COMMENT='RAG query log tracking contract search queries, retrieval counts, response times, and relevance scores'
;
create or replace cortex search service INSURANCE_AI_HUB.DOCUMENTS.POLICY_SEARCH_SERVICE
	ON CHUNK_TEXT
	attributes DOCUMENT_ID,CHUNK_INDEX
	warehouse='INSURANCE_AI_HUB_WH'
	target_lag='1 hour'
	comment='Cortex Search service for RAG over policy document chunks - enables natural language retrieval of coverage terms, exclusions, and conditions'
	refresh_mode=INCREMENTAL
	as SELECT
    CHUNK_ID,
    DOCUMENT_ID,
    CHUNK_INDEX,
    CHUNK_TEXT,
    TOKEN_COUNT,
    EMBEDDING_MODEL
  FROM INSURANCE_AI_HUB.DOCUMENTS.DOCUMENT_CHUNKS;
create or replace schema INSURANCE_AI_HUB.EXTERNAL_DATA COMMENT='External data proxies simulating Marketplace listings (NOAA weather, FRED economics, FEMA risk, NAIC guidelines). Replace with real Marketplace installs for production.';

create or replace TABLE INSURANCE_AI_HUB.EXTERNAL_DATA.NAIC_STATUTORY_GUIDELINES (
	GUIDELINE_ID VARCHAR(20) NOT NULL,
	STATE VARCHAR(2) NOT NULL,
	LINE_OF_BUSINESS VARCHAR(40) NOT NULL,
	MIN_RESERVE_RATIO NUMBER(5,2) NOT NULL,
	MAX_COMBINED_RATIO NUMBER(5,2) NOT NULL,
	MIN_CAPITAL_ADEQUACY NUMBER(5,2) NOT NULL,
	MIN_SURPLUS_RATIO NUMBER(5,2) NOT NULL,
	EFFECTIVE_YEAR NUMBER(38,0) NOT NULL,
	SOURCE VARCHAR(30) NOT NULL DEFAULT 'NAIC Model Act',
	constraint PK_NAIC primary key (GUIDELINE_ID)
)COMMENT='NAIC statutory guideline reference — minimum reserve ratios and combined ratio thresholds by state and LOB'
;
create or replace TABLE INSURANCE_AI_HUB.EXTERNAL_DATA.STATE_FIPS_LOOKUP (
	STATE_ABBREV VARCHAR(2) NOT NULL,
	STATE_NAME VARCHAR(50) NOT NULL,
	STATE_GEO_ID VARCHAR(20) NOT NULL,
	STATE_FIPS VARCHAR(2) NOT NULL,
	constraint PK_STATE_FIPS primary key (STATE_ABBREV)
)COMMENT='State FIPS code lookup bridging 2-letter abbreviations to Snowflake Public Data GEO_IDs'
;
create or replace view INSURANCE_AI_HUB.EXTERNAL_DATA.FRED_SERIES_CATALOG(
	SERIES_ID,
	SERIES_NAME,
	UNITS,
	FREQUENCY,
	SEASONAL_ADJUSTMENT,
	EARLIEST_DATE,
	LATEST_DATE,
	OBSERVATION_COUNT,
	LAST_UPDATED
) as
SELECT
    SERIES_ID,
    SERIES_NAME,
    UNITS,
    FREQUENCY,
    SEASONAL_ADJUSTMENT,
    MIN(DATE) AS EARLIEST_DATE,
    MAX(DATE) AS LATEST_DATE,
    COUNT(*) AS OBSERVATION_COUNT,
    MAX(LAST_UPDATED_AT) AS LAST_UPDATED
FROM FRED_FEDERAL_RESERVE_ECONOMIC_DATA_SERIES_OBSERVATIONS.FRED.FRED_SERIES_OBSERVATIONS_VW
GROUP BY 1, 2, 3, 4, 5;
create or replace view INSURANCE_AI_HUB.EXTERNAL_DATA.LIVE_BLS_CPI_DATA(
	GEO_ID,
	SERIES_ID,
	SERIES_NAME,
	OBSERVATION_DATE,
	VALUE,
	UNIT,
	FREQUENCY
) as
SELECT
    GEO_ID,
    VARIABLE                                AS SERIES_ID,
    VARIABLE_NAME                           AS SERIES_NAME,
    DATE                                    AS OBSERVATION_DATE,
    VALUE,
    CASE
        WHEN VARIABLE_NAME ILIKE '%index%' THEN 'Index'
        WHEN VARIABLE_NAME ILIKE '%percent%' THEN 'Percent'
        WHEN VARIABLE_NAME ILIKE '%average price%' THEN 'USD'
        ELSE 'Index'
    END                                     AS UNIT,
    CASE
        WHEN VARIABLE_NAME ILIKE '%monthly%' THEN 'Monthly'
        WHEN VARIABLE_NAME ILIKE '%quarterly%' THEN 'Quarterly'
        WHEN VARIABLE_NAME ILIKE '%annual%' THEN 'Annual'
        ELSE 'Monthly'
    END                                     AS FREQUENCY
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.BUREAU_OF_LABOR_STATISTICS_PRICE_TIMESERIES
WHERE GEO_ID = 'country/USA'
  AND DATE >= '2020-01-01';
create or replace view INSURANCE_AI_HUB.EXTERNAL_DATA.LIVE_FEMA_DISASTER_DECLARATIONS(
	RECORD_ID,
	DISASTER_ID,
	DESIGNATED_AREA,
	STATE,
	COUNTY_FIPS,
	FEMA_REGION,
	TRIBAL_REQUEST,
	PROGRAMS,
	DESIGNATED_DATE,
	ENTRY_DATE,
	UPDATE_DATE,
	CLOSEOUT_DATE
) as
SELECT
    DISASTER_DECLARATION_RECORD_ID          AS RECORD_ID,
    DISASTER_ID,
    FEMA_DESIGNATED_AREA                    AS DESIGNATED_AREA,
    s.STATE_ABBREV                          AS STATE,
    REPLACE(fda.COUNTY_GEO_ID, 'geoId/', '') AS COUNTY_FIPS,
    FEMA_REGION_ID                          AS FEMA_REGION,
    TRIBAL_REQUEST,
    DECLARED_PROGRAMS_DETAILED              AS PROGRAMS,
    DESIGNATED_DATE,
    ENTRY_DATE,
    UPDATE_DATE,
    CLOSEOUT_DATE
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.FEMA_DISASTER_DECLARATION_AREAS_INDEX fda
LEFT JOIN INSURANCE_AI_HUB.EXTERNAL_DATA.STATE_FIPS_LOOKUP s
    ON s.STATE_GEO_ID = fda.STATE_GEO_ID
WHERE DESIGNATED_DATE IS NOT NULL;
create or replace view INSURANCE_AI_HUB.EXTERNAL_DATA.LIVE_FEMA_FLOOD_CLAIMS(
	CLAIM_ID,
	STATE,
	CITY,
	ZIP_CODE,
	OCCUPANCY_TYPE,
	BUILDING_TYPE,
	FLOOD_EVENT,
	CAUSE_OF_DAMAGE,
	DATE_OF_LOSS,
	BUILDING_PROPERTY_VALUE,
	BUILDING_DAMAGE_AMOUNT,
	AMOUNT_PAID_ON_BUILDING_CLAIM,
	CONTENTS_DAMAGE_AMOUNT,
	AMOUNT_PAID_ON_CONTENTS_CLAIM,
	CURRENT_FLOOD_ZONE,
	NUMBER_OF_FLOORS,
	ORIGINAL_CONSTRUCTION_DATE,
	LATITUDE,
	LONGITUDE
) as
SELECT
    NATIONAL_FLOOD_INSURANCE_PROGRAM_CLAIM_ID   AS CLAIM_ID,
    s.STATE_ABBREV                              AS STATE,
    CITY,
    REPLACE(nfip.ZIP_GEO_ID, 'zip/', '')        AS ZIP_CODE,
    OCCUPANCY_TYPE,
    BUILDING_TYPE,
    FLOOD_EVENT,
    CAUSE_OF_DAMAGE,
    DATE_OF_LOSS,
    BUILDING_PROPERTY_VALUE,
    BUILDING_DAMAGE_AMOUNT,
    AMOUNT_PAID_ON_BUILDING_CLAIM,
    CONTENTS_DAMAGE_AMOUNT,
    AMOUNT_PAID_ON_CONTENTS_CLAIM,
    CURRENT_FLOOD_ZONE,
    NUMBER_OF_FLOORS,
    ORIGINAL_CONSTRUCTION_DATE,
    LATITUDE,
    LONGITUDE
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.FEMA_NATIONAL_FLOOD_INSURANCE_PROGRAM_CLAIM_INDEX nfip
LEFT JOIN INSURANCE_AI_HUB.EXTERNAL_DATA.STATE_FIPS_LOOKUP s
    ON s.STATE_GEO_ID = nfip.STATE_GEO_ID;
create or replace view INSURANCE_AI_HUB.EXTERNAL_DATA.LIVE_FEMA_FLOOD_POLICIES(
	NATIONAL_FLOOD_INSURANCE_PROGRAM_POLICY_ID,
	BUILDING_TYPE,
	OCCUPANCY_TYPE,
	TOTAL_BUILDING_INSURANCE_COVERAGE,
	BUILDING_DEDUCTIBLE,
	TOTAL_CONTENTS_INSURANCE_COVERAGE,
	CONTENTS_DEDUCTIBLE,
	TOTAL_INSURANCE_PREMIUM_OF_THE_POLICY,
	POLICY_COST,
	POLICY_COUNT,
	BUILDING_REPLACEMENT_COST,
	INSURANCE_TO_VALUE_RATIO,
	PROPERTY_INDICATORS,
	BASIC_BUILDING_RATE,
	BASIC_CONTENTS_RATE,
	ADDITIONAL_BUILDING_RATE,
	ADDITIONAL_CONTENTS_RATE,
	PROBATION_SURCHARGE,
	FEDERAL_POLICY_FEE,
	HFIAA_SURCHARGE,
	ICC_PREMIUM,
	POLICY_RATING_METHOD,
	SUBSIDIZATION_TYPE,
	WAITING_PERIOD_TYPE,
	ORIGINAL_CONSTRUCTION_DATE,
	PROPERTY_PURCHASE_DATE,
	ORIGINAL_FLOOD_POLICY_DATE,
	POLICY_EFFECTIVE_DATE,
	POLICY_TERMINATION_DATE,
	POLICY_CANCELLATION_DATE,
	ENDORSEMENT_EFFECTIVE_DATE,
	POLICY_CANCELLATION_REASON,
	NUMBER_OF_FLOORS,
	BASE_FLOOD_ELEVATION,
	LOWEST_FLOOR_ELEVATION,
	ELEVATION_DIFFERENCE,
	CURRENT_FLOOD_ZONE,
	POLICY_RATED_FLOOD_ZONE,
	CONTENT_LOCATION,
	LOWEST_ADJACENT_GRADE,
	CONDOMINIUM_COVERAGE_TYPE,
	COMMUNITY_RATING_SYSTEM_CLASS,
	DISASTER_ASSISTANCE_COVERAGE_REQUIRED,
	GRANDFATHERING,
	ROLLOVER_TRANSFER,
	BASEMENT_ENCLOSURE_CRAWLSPACE,
	ENCLOSURE,
	OBSTRUCTION,
	RESERVE_FUND_ASSESSMENT,
	MAP_PANEL_NUMBER,
	MAP_PANEL_SUFFIX,
	FEMA_REGION_ID,
	NFIP_RATED_COMMUNITY_NUMBER,
	NFIP_COMMUNITY_NUMBER_CURRENT,
	NFIP_COMMUNITY_NAME,
	STATE_GEO_ID,
	COUNTY_GEO_ID,
	ZIP_GEO_ID,
	CENSUS_TRACT_ID,
	CENSUS_BLOCK_GROUP_ID,
	CITY,
	LATITUDE,
	LONGITUDE,
	STATE
) as
SELECT
    nfip.*,
    s.STATE_ABBREV AS STATE
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.FEMA_NATIONAL_FLOOD_INSURANCE_PROGRAM_POLICY_INDEX nfip
LEFT JOIN INSURANCE_AI_HUB.EXTERNAL_DATA.STATE_FIPS_LOOKUP s
    ON s.STATE_GEO_ID = nfip.STATE_GEO_ID;
create or replace view INSURANCE_AI_HUB.EXTERNAL_DATA.LIVE_FRED_ECONOMIC_DATA(
	OBSERVATION_ID,
	SERIES_ID,
	SERIES_NAME,
	OBSERVATION_DATE,
	VALUE,
	UNIT,
	FREQUENCY,
	SEASONAL_ADJUSTMENT,
	LAST_UPDATED_AT
) as
SELECT
    ID                      AS OBSERVATION_ID,
    SERIES_ID,
    SERIES_NAME,
    DATE                    AS OBSERVATION_DATE,
    VALUE,
    UNITS                   AS UNIT,
    FREQUENCY,
    SEASONAL_ADJUSTMENT,
    LAST_UPDATED_AT
FROM FRED_FEDERAL_RESERVE_ECONOMIC_DATA_SERIES_OBSERVATIONS.FRED.FRED_SERIES_OBSERVATIONS_VW
WHERE SERIES_ID IN (
    'CPIAUCSL',           -- CPI All Urban Consumers
    'CUSR0000SETD',       -- CPI Vehicle Repair
    'CUSR0000SAM',        -- CPI Medical Care
    'CUSR0000SAH1',       -- CPI Shelter
    'CUSR0000SETB01',     -- CPI Auto Insurance
    'UNRATE',             -- Unemployment Rate
    'FEDFUNDS',           -- Federal Funds Rate
    'DGS10',              -- 10-Year Treasury Yield
    'MORTGAGE30US',       -- 30-Year Mortgage Rate
    'PPIACO',             -- Producer Price Index
    'TOTALSA',            -- Total Vehicle Sales
    'PCE',                -- Personal Consumption Expenditure
    'GDP',                -- Gross Domestic Product
    'DEXUSEU',            -- USD/EUR Exchange Rate
    'SP500'               -- S&P 500
);
create or replace view INSURANCE_AI_HUB.EXTERNAL_DATA.LIVE_HOSPITAL_PRICE_TRANSPARENCY(
	HOSPITAL_CCN,
	BILLING_CODE,
	CODE_TYPE,
	PROCEDURE_DESCRIPTION,
	PAYER,
	PLAN_NAME,
	RATE_TYPE,
	RATE_AMOUNT,
	RATE_METHODOLOGY,
	SNAPSHOT_DATE
) as
SELECT
    ""ccn""                       AS HOSPITAL_CCN,
    ""billing_code""              AS BILLING_CODE,
    ""billing_code_type""         AS CODE_TYPE,
    ""billing_code_description""  AS PROCEDURE_DESCRIPTION,
    ""payer_name_canonical""      AS PAYER,
    ""plan_name""                 AS PLAN_NAME,
    ""rate_type""                 AS RATE_TYPE,
    ""rate_amount""               AS RATE_AMOUNT,
    ""rate_methodology""          AS RATE_METHODOLOGY,
    ""snapshot_date""             AS SNAPSHOT_DATE
FROM HEALTHPARSE_HOSPITAL_PRICE_TRANSPARENCY_RATES.HPT_NEGOTIATED_RATES_SAMPLE.HPT_NEGOTIATED_RATES;
create or replace view INSURANCE_AI_HUB.EXTERNAL_DATA.LIVE_NWS_WEATHER_ALERTS(
	ALERT_ID,
	COUNTY_FIPS,
	STATE,
	EVENT_TYPE,
	EVENT_SEVERITY,
	EVENT_URGENCY,
	EVENT_CERTAINTY,
	ALERT_STATUS,
	ALERT_TYPE,
	ALERT_TITLE,
	ALERT_DESCRIPTION,
	EVENT_BEGIN,
	EVENT_END,
	REPORTED_DATE,
	SOURCE
) as
SELECT
    NWS_ALERT_ID                            AS ALERT_ID,
    REPLACE(COUNTY_GEO_ID, 'geoId/', '')    AS COUNTY_FIPS,
    s.STATE_ABBREV                          AS STATE,
    EVENT_TYPE,
    EVENT_SEVERITY,
    EVENT_URGENCY,
    EVENT_CERTAINTY,
    ALERT_STATUS,
    ALERT_TYPE,
    ALERT_TITLE,
    ALERT_DESCRIPTION,
    ONSET_TIMESTAMP                         AS EVENT_BEGIN,
    END_TIMESTAMP                           AS EVENT_END,
    SENT_TIMESTAMP                          AS REPORTED_DATE,
    NWS_REPORTER                            AS SOURCE
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.NWS_WEATHER_ALERT_EVENTS nws
LEFT JOIN INSURANCE_AI_HUB.EXTERNAL_DATA.STATE_FIPS_LOOKUP s
    ON s.STATE_FIPS = LEFT(REPLACE(nws.COUNTY_GEO_ID, 'geoId/', ''), 2)::INT
WHERE ONSET_TIMESTAMP >= '2022-01-01';
create or replace view INSURANCE_AI_HUB.EXTERNAL_DATA.V_CPI_INSURANCE_INDICES(
	OBSERVATION_DATE,
	SERIES_ID,
	SERIES_NAME,
	INDEX_VALUE,
	GEO_ID,
	INSURANCE_CATEGORY
) as
SELECT bls.DATE AS OBSERVATION_DATE, bls.VARIABLE AS SERIES_ID, bls.VARIABLE_NAME AS SERIES_NAME,
    bls.VALUE AS INDEX_VALUE, bls.GEO_ID,
    CASE WHEN bls.VARIABLE LIKE '%Motor_vehicle_insurance%' THEN 'Auto Insurance'
         WHEN bls.VARIABLE LIKE '%Motor_vehicle_maintenance%' OR bls.VARIABLE LIKE '%Motor_vehicle_parts%' THEN 'Vehicle Repair'
         WHEN bls.VARIABLE LIKE '%Medical_care%' THEN 'Medical Care'
         WHEN bls.VARIABLE LIKE '%Shelter%' OR bls.VARIABLE LIKE '%shelter%' THEN 'Shelter'
         WHEN bls.VARIABLE LIKE '%All_items%' AND bls.VARIABLE NOT LIKE '%less%' THEN 'All Items'
         WHEN bls.VARIABLE LIKE '%Tenants%' OR bls.VARIABLE LIKE '%renters%' THEN 'Renters Insurance'
         ELSE 'Other' END AS INSURANCE_CATEGORY
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.BUREAU_OF_LABOR_STATISTICS_PRICE_TIMESERIES bls
WHERE bls.VARIABLE LIKE ANY (
    'CPI:_Motor_vehicle_insurance%Monthly%','CPI:_Motor_vehicle_maintenance%Monthly%',
    'CPI:_Motor_vehicle_parts%Monthly%','CPI:_Medical_care,%Monthly%',
    'CPI:_Medical_care_services%Monthly%','CPI:_Shelter%Monthly%',
    'CPI:_All_items,%Monthly%','CPI:_Tenants%Monthly%')
AND bls.VARIABLE LIKE '%Not_seasonally_adjusted%' AND bls.GEO_ID = 'country/USA';
create or replace view INSURANCE_AI_HUB.EXTERNAL_DATA.V_FEMA_DISASTER_HISTORY(
	DISASTER_ID,
	FEMA_DESIGNATED_AREA,
	STATE,
	COUNTY_GEO_ID,
	FEMA_REGION_ID,
	DECLARED_PROGRAMS_DETAILED,
	DESIGNATED_DATE,
	DISASTER_DECLARATION_NAME,
	DISASTER_DECLARATION_TYPE,
	DISASTER_TYPE,
	DISASTER_DECLARATION_DATE,
	DISASTER_BEGIN_DATE,
	DISASTER_END_DATE,
	DECLARED_PROGRAMS,
	APPROVED_INDIVIDUAL_ASSISTANCE_APPLICATIONS,
	IHP_AMOUNT,
	HA_AMOUNT,
	ONA_AMOUNT,
	PA_AMOUNT,
	HM_AMOUNT
) as
SELECT dd.DISASTER_ID, dd.FEMA_DESIGNATED_AREA, sl.STATE_ABBREV AS STATE, dd.COUNTY_GEO_ID,
    dd.FEMA_REGION_ID, dd.DECLARED_PROGRAMS_DETAILED, dd.DESIGNATED_DATE,
    di.DISASTER_DECLARATION_NAME, di.DISASTER_DECLARATION_TYPE, di.DISASTER_TYPE,
    di.DISASTER_DECLARATION_DATE, di.DISASTER_BEGIN_DATE, di.DISASTER_END_DATE,
    di.DECLARED_PROGRAMS,
    di.APPROVED_INDIVIDUAL_ASSISTANCE_APPLICATIONS,
    di.APPROVED_INDIVIDUAL_AND_HOUSEHOLDS_PROGRAM_AMOUNT AS IHP_AMOUNT,
    di.APPROVED_HOUSING_ASSISTANCE_AMOUNT AS HA_AMOUNT,
    di.APPROVED_OTHER_NEEDS_ASSISTANCE_AMOUNT AS ONA_AMOUNT,
    di.STATE_OBLIGATED_PUBLIC_ASSISTANCE_AMOUNT AS PA_AMOUNT,
    di.STATE_OBLIGATED_HAZARD_MITIGATION_GRANT_PROGRAM_AMOUNT AS HM_AMOUNT
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.FEMA_DISASTER_DECLARATION_AREAS_INDEX dd
JOIN SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.FEMA_DISASTER_DECLARATION_INDEX di ON dd.DISASTER_ID = di.DISASTER_ID
LEFT JOIN INSURANCE_AI_HUB.EXTERNAL_DATA.STATE_FIPS_LOOKUP sl ON dd.STATE_GEO_ID = sl.STATE_GEO_ID;
create or replace view INSURANCE_AI_HUB.EXTERNAL_DATA.V_FEMA_FLOOD_CLAIMS(
	NFIP_CLAIM_ID,
	STATE,
	ZIP_CODE,
	BUILDING_TYPE,
	OCCUPANCY_TYPE,
	UNITS,
	FLOOD_EVENT,
	FLOOD_TYPE,
	FLOOD_WATER_DURATION_HOURS,
	FLOOD_WATER_DEPTH,
	CAUSE_OF_DAMAGE,
	DATE_OF_LOSS,
	BUILDING_PROPERTY_VALUE,
	BUILDING_DAMAGE_AMOUNT,
	AMOUNT_PAID_ON_BUILDING_CLAIM,
	CONTENTS_PROPERTY_VALUE,
	CONTENTS_DAMAGE_AMOUNT,
	AMOUNT_PAID_ON_CONTENTS_CLAIM,
	TOTAL_BUILDING_INSURANCE_COVERAGE,
	BUILDING_DEDUCTIBLE,
	ORIGINAL_CONSTRUCTION_DATE,
	NUMBER_OF_FLOORS,
	BASE_FLOOD_ELEVATION,
	LOWEST_FLOOR_ELEVATION,
	ELEVATION_DIFFERENCE,
	CURRENT_FLOOD_ZONE,
	POLICY_RATED_FLOOD_ZONE,
	BASEMENT_ENCLOSURE_CRAWLSPACE,
	CITY,
	LATITUDE,
	LONGITUDE
) as
SELECT fc.NATIONAL_FLOOD_INSURANCE_PROGRAM_CLAIM_ID AS NFIP_CLAIM_ID,
    sl.STATE_ABBREV AS STATE, REPLACE(fc.ZIP_GEO_ID, 'zip/', '') AS ZIP_CODE,
    fc.BUILDING_TYPE, fc.OCCUPANCY_TYPE, fc.UNITS,
    fc.FLOOD_EVENT, fc.FLOOD_TYPE, fc.FLOOD_WATER_DURATION_HOURS, fc.FLOOD_WATER_DEPTH,
    fc.CAUSE_OF_DAMAGE, fc.DATE_OF_LOSS,
    fc.BUILDING_PROPERTY_VALUE, fc.BUILDING_DAMAGE_AMOUNT, fc.AMOUNT_PAID_ON_BUILDING_CLAIM,
    fc.CONTENTS_PROPERTY_VALUE, fc.CONTENTS_DAMAGE_AMOUNT, fc.AMOUNT_PAID_ON_CONTENTS_CLAIM,
    fc.TOTAL_BUILDING_INSURANCE_COVERAGE, fc.BUILDING_DEDUCTIBLE,
    fc.ORIGINAL_CONSTRUCTION_DATE, fc.NUMBER_OF_FLOORS,
    fc.BASE_FLOOD_ELEVATION, fc.LOWEST_FLOOR_ELEVATION, fc.ELEVATION_DIFFERENCE,
    fc.CURRENT_FLOOD_ZONE, fc.POLICY_RATED_FLOOD_ZONE,
    fc.BASEMENT_ENCLOSURE_CRAWLSPACE, fc.CITY, fc.LATITUDE, fc.LONGITUDE
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.FEMA_NATIONAL_FLOOD_INSURANCE_PROGRAM_CLAIM_INDEX fc
LEFT JOIN INSURANCE_AI_HUB.EXTERNAL_DATA.STATE_FIPS_LOOKUP sl ON fc.STATE_GEO_ID = sl.STATE_GEO_ID;
create or replace view INSURANCE_AI_HUB.EXTERNAL_DATA.V_FEMA_FLOOD_POLICIES(
	NFIP_POLICY_ID,
	STATE,
	ZIP_CODE,
	CITY,
	BUILDING_TYPE,
	OCCUPANCY_TYPE,
	NUMBER_OF_FLOORS,
	ORIGINAL_CONSTRUCTION_DATE,
	BUILDING_REPLACEMENT_COST,
	TOTAL_BUILDING_INSURANCE_COVERAGE,
	BUILDING_DEDUCTIBLE,
	TOTAL_CONTENTS_INSURANCE_COVERAGE,
	CONTENTS_DEDUCTIBLE,
	PREMIUM,
	POLICY_COST,
	INSURANCE_TO_VALUE_RATIO,
	CURRENT_FLOOD_ZONE,
	POLICY_RATED_FLOOD_ZONE,
	BASE_FLOOD_ELEVATION,
	LOWEST_FLOOR_ELEVATION,
	ELEVATION_DIFFERENCE,
	BASEMENT_ENCLOSURE_CRAWLSPACE,
	COMMUNITY_RATING_SYSTEM_CLASS,
	POLICY_EFFECTIVE_DATE,
	POLICY_TERMINATION_DATE,
	POLICY_CANCELLATION_DATE,
	POLICY_CANCELLATION_REASON,
	POLICY_RATING_METHOD,
	SUBSIDIZATION_TYPE,
	LATITUDE,
	LONGITUDE
) as
SELECT fp.NATIONAL_FLOOD_INSURANCE_PROGRAM_POLICY_ID AS NFIP_POLICY_ID,
    sl.STATE_ABBREV AS STATE, REPLACE(fp.ZIP_GEO_ID, 'zip/', '') AS ZIP_CODE, fp.CITY,
    fp.BUILDING_TYPE, fp.OCCUPANCY_TYPE, fp.NUMBER_OF_FLOORS,
    fp.ORIGINAL_CONSTRUCTION_DATE, fp.BUILDING_REPLACEMENT_COST,
    fp.TOTAL_BUILDING_INSURANCE_COVERAGE, fp.BUILDING_DEDUCTIBLE,
    fp.TOTAL_CONTENTS_INSURANCE_COVERAGE, fp.CONTENTS_DEDUCTIBLE,
    fp.TOTAL_INSURANCE_PREMIUM_OF_THE_POLICY AS PREMIUM, fp.POLICY_COST,
    fp.INSURANCE_TO_VALUE_RATIO, fp.CURRENT_FLOOD_ZONE, fp.POLICY_RATED_FLOOD_ZONE,
    fp.BASE_FLOOD_ELEVATION, fp.LOWEST_FLOOR_ELEVATION, fp.ELEVATION_DIFFERENCE,
    fp.BASEMENT_ENCLOSURE_CRAWLSPACE, fp.COMMUNITY_RATING_SYSTEM_CLASS,
    fp.POLICY_EFFECTIVE_DATE, fp.POLICY_TERMINATION_DATE,
    fp.POLICY_CANCELLATION_DATE, fp.POLICY_CANCELLATION_REASON,
    fp.POLICY_RATING_METHOD, fp.SUBSIDIZATION_TYPE, fp.LATITUDE, fp.LONGITUDE
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.FEMA_NATIONAL_FLOOD_INSURANCE_PROGRAM_POLICY_INDEX fp
LEFT JOIN INSURANCE_AI_HUB.EXTERNAL_DATA.STATE_FIPS_LOOKUP sl ON fp.STATE_GEO_ID = sl.STATE_GEO_ID;
create or replace view INSURANCE_AI_HUB.EXTERNAL_DATA.V_ZIP_DEMOGRAPHICS(
	ZIP_CODE,
	VARIABLE,
	VARIABLE_NAME,
	SURVEY_DATE,
	VALUE,
	UNIT
) as
SELECT REPLACE(acs.GEO_ID, 'zip/', '') AS ZIP_CODE, acs.VARIABLE, acs.VARIABLE_NAME,
    acs.DATE AS SURVEY_DATE, acs.VALUE, acs.UNIT
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.AMERICAN_COMMUNITY_SURVEY_TIMESERIES acs
WHERE acs.GEO_ID LIKE 'zip/%';
create or replace schema INSURANCE_AI_HUB.PUBLIC;

create or replace TABLE INSURANCE_AI_HUB.PUBLIC.EVAL_DATASET_EDIE_20260831_074749 (
	QUESTION_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	INPUT_QUERY VARCHAR(16777216) NOT NULL,
	GROUND_TRUTH VARIANT NOT NULL,
	CATEGORY VARCHAR(16777216),
	TRACK VARCHAR(16777216) NOT NULL,
	AUTHOR VARCHAR(16777216) DEFAULT CURRENT_USER(),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	NOTES VARCHAR(16777216),
	unique (INPUT_QUERY)
);
create or replace TABLE INSURANCE_AI_HUB.PUBLIC.EVAL_DATASET_EDIE_20260831_084744 (
	QUESTION_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	INPUT_QUERY VARCHAR(16777216) NOT NULL,
	GROUND_TRUTH VARIANT NOT NULL,
	CATEGORY VARCHAR(16777216),
	TRACK VARCHAR(16777216) NOT NULL,
	AUTHOR VARCHAR(16777216) DEFAULT CURRENT_USER(),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	NOTES VARCHAR(16777216),
	unique (INPUT_QUERY)
);
create or replace TABLE INSURANCE_AI_HUB.PUBLIC.EVAL_DATASET_EDIE_20260831_111623 (
	QUESTION_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	INPUT_QUERY VARCHAR(16777216) NOT NULL,
	GROUND_TRUTH VARIANT NOT NULL,
	CATEGORY VARCHAR(16777216),
	TRACK VARCHAR(16777216) NOT NULL,
	AUTHOR VARCHAR(16777216) DEFAULT CURRENT_USER(),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	NOTES VARCHAR(16777216),
	unique (INPUT_QUERY)
);