SELECT COUNT(CASE WHEN STATUS = 'Bound' OR BOUND_DATE IS NOT NULL THEN 1 END) AS total_binds, COUNT(*) AS total_quotes, ROUND(COUNT(CASE WHEN STATUS = 'Bound' OR BOUND_DATE IS NOT NULL THEN 1 END) * 100.0 / NULLIF(COUNT(*), 0), 1) AS quote_to_bind_ratio_pct FROM INSURANCE_AI_HUB.ANALYTICS.APPLICATIONS WHERE DATE_TRUNC('month', APPLICATION_DATE) = DATE_TRUNC('month', DATEADD('month', -5, CURRENT_DATE()))




select *  FROM INSURANCE_AI_HUB.ANALYTICS.APPLICATIONS;