SELECT w.STATE AS STATE, COUNT(*) AS VALUE FROM INSURANCE_AI_HUB.EXTERNAL_DATA.LIVE_NWS_WEATHER_ALERTS w  WHERE w.STATE IS NOT NULL AND w.REPORTED_DATE >= '2026-01-01' AND w.STATE IS NOT NULL GROUP BY w.STATE ORDER BY VALUE DESC LIMIT 50
;



select distinct event_type from INSURANCE_AI_HUB.EXTERNAL_DATA.LIVE_NWS_WEATHER_ALERTS;


select * FROM INSURANCE_AI_HUB.ANALYTICS.CHAT_HISTORY WHERE SESSION_ID = 'test-123'
